package src;

import ErroresInterfaz.*;

public class InterfazConfirmarCuenta extends javax.swing.JFrame 
{
    /**
     * Creates new form InterfazConfirmarCuenta
     */
    public InterfazConfirmarCuenta() {
        initComponents();
        
        verificado = false;
        labelVerificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelVerificar = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        labelErrorCodigo = new javax.swing.JLabel();
        botonVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        labelVerificar.setText("Para verificar su cuenta, escriba el código que le ha llegado a su correo:");
        labelVerificar.setToolTipText("");

        campoCodigo.setText("Código*");
        campoCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoFocusLost(evt);
            }
        });

        labelErrorCodigo.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        labelErrorCodigo.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorCodigo.setText("                                         ");

        botonVerificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonVerificar.setText("Verificar");
        botonVerificar.setFocusable(false);
        botonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelErrorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(botonVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVerificar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoFocusGained
        if(campoCodigo.getText().equals("Código*"))
        {
            campoCodigo.setText("");
        }
    }//GEN-LAST:event_campoCodigoFocusGained

    private void campoCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoFocusLost
        if(campoCodigo.getText().equals(""))
        {
            campoCodigo.setText("Código*");
        }
    }//GEN-LAST:event_campoCodigoFocusLost

    private void botonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerificarActionPerformed
        if(!campoCodigo.getText().equals(EnviarCorreo.getInstancia().getNumeroAleatorio()))
        {
            new ErrorConfirmarCuenta();
        }
        else if(campoCodigo.getText().equals("Código*"))
        {
            labelErrorCodigo.setText("El campo esta vacío");
        }
        else
        {
            labelErrorCodigo.setText("                                   ");
            InterfazCrearCuenta.getInstancia().cuentaBD();
        }
        dispose();
    }//GEN-LAST:event_botonVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerificar;
    public javax.swing.JTextField campoCodigo;
    private javax.swing.JLabel labelErrorCodigo;
    private javax.swing.JLabel labelVerificar;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
    public boolean verificado;
}
