package src;

import java.io.*;
import java.sql.*;
import java.util.regex.*;

public class InterfazCrearCuenta extends javax.swing.JFrame 
{
    /**
     * Creates new form InterfazLogin
     */
    public InterfazCrearCuenta() 
    {
        initComponents();
        panelCrearCuenta.requestFocusInWindow();
    }
    
    public static InterfazCrearCuenta getInstancia()
    {
        if(instancia == null)
        {
            instancia = new InterfazCrearCuenta();
        }
        return instancia;
    }
    
    public static InterfazCrearCuenta crearNuevaInstancia() 
    {
        instancia = null;
        return getInstancia();
    }
    
    public static boolean longitudMinima(String password) 
    {
        return password.length() >= 8;
    }

    public static boolean tieneNumero(String password) 
    {
        Pattern pattern = Pattern.compile("[0-9]");
        Matcher matcher = pattern.matcher(password);
        return matcher.find();
    }

    public static boolean tieneMayuscula(String password) 
    {
        Pattern pattern = Pattern.compile("[A-Z]");
        Matcher matcher = pattern.matcher(password);
        return matcher.find();
    }

    public static boolean tieneCaracterEspecial(String password) 
    {
        Pattern pattern = Pattern.compile("[^A-Za-z0-9]");
        Matcher matcher = pattern.matcher(password);
        return matcher.find();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        panelCrearCuenta = new javax.swing.JPanel();
        campoEmail = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        labelCrearCuenta = new javax.swing.JLabel();
        labelContraseña1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        labelVIniciarSesion = new javax.swing.JLabel();
        labelErrorEmail = new javax.swing.JLabel();
        labelErrorUsuario = new javax.swing.JLabel();
        labelErrorContraseña = new javax.swing.JLabel();
        labelErrorCContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        butonCrearCuenta = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        labelOjo1 = new javax.swing.JLabel();
        labelOjo2 = new javax.swing.JLabel();
        campoCContraseña = new javax.swing.JPasswordField();
        campoContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelCrearCuenta.setBackground(new java.awt.Color(255, 255, 255));
        panelCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        panelCrearCuenta.setPreferredSize(new java.awt.Dimension(400, 540));
        panelCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedPanelActionEvent(evt);
            }
        });

        campoEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(153, 153, 153));
        campoEmail.setText("E-mail*");
        campoEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focusLostEmailActionEvent(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelEmail.setText("E-mail");

        labelContraseña.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelContraseña.setText("Contraseña");

        labelCrearCuenta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelCrearCuenta.setText("Crear Cuenta");
        labelCrearCuenta.setVerifyInputWhenFocusTarget(false);

        labelContraseña1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelContraseña1.setText("Confirmar contraseña");

        labelUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelUsuario.setText("Usuario");

        campoUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText("Usuario*");
        campoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUsuariofocusLostEmailActionEvent(evt);
            }
        });

        labelVIniciarSesion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelVIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        labelVIniciarSesion.setText("Volver para iniciar sesión");
        labelVIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVIniciarSesionActionPerformed(evt);
            }
        });

        labelErrorEmail.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        labelErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorEmail.setText("                            ");

        labelErrorUsuario.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        labelErrorUsuario.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorUsuario.setText("                            ");

        labelErrorContraseña.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        labelErrorContraseña.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorContraseña.setText("                            ");

        labelErrorCContraseña.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        labelErrorCContraseña.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorCContraseña.setText("                            ");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("¿Ya tienes cuenta?");

        butonCrearCuenta.setText("Crear cuenta");
        butonCrearCuenta.setToolTipText("");
        butonCrearCuenta.setFocusPainted(false);
        butonCrearCuenta.setFocusable(false);
        butonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCrearCuentaActionPerformed(evt);
            }
        });

        jSeparator.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        labelOjo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOjo1.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "ojoVisible.png"));
        labelOjo1.setText(" ");
        labelOjo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOjo1MouseClicked(evt);
            }
        });

        labelOjo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOjo2.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "ojoVisible.png"));
        labelOjo2.setText(" ");
        labelOjo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOjo2MouseClicked(evt);
            }
        });

        campoCContraseña.setText("Confirmar contraseña*");
        campoCContraseña.setEchoChar('*');
        campoCContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCContraseñaFocusLost(evt);
            }
        });

        campoContraseña.setText("Contraseña*");
        campoContraseña.setEchoChar('*');
        campoContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoContraseñaFocusLost(evt);
            }
        });
        campoContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoContraseñaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelCrearCuentaLayout = new javax.swing.GroupLayout(panelCrearCuenta);
        panelCrearCuenta.setLayout(panelCrearCuentaLayout);
        panelCrearCuentaLayout.setHorizontalGroup(
            panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelErrorCContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelErrorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(labelCrearCuenta))
                        .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(butonCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelUsuario)
                                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelContraseña1)
                                .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                                    .addComponent(campoCContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(labelOjo2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelContraseña)
                                .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                                    .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(labelOjo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelEmail)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                .addComponent(labelErrorUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelVIniciarSesion)
                                .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, 0))
        );
        panelCrearCuentaLayout.setVerticalGroup(
            panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelEmail)
                .addGap(0, 0, 0)
                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorEmail)
                .addGap(10, 10, 10)
                .addComponent(labelUsuario)
                .addGap(0, 0, 0)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorUsuario)
                .addGap(10, 10, 10)
                .addComponent(labelContraseña)
                .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOjo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorContraseña)
                .addGap(10, 10, 10)
                .addComponent(labelContraseña1)
                .addGap(0, 0, 0)
                .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOjo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErrorCContraseña)
                .addGap(10, 10, 10)
                .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                        .addComponent(butonCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(panelCrearCuentaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(labelVIniciarSesion)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mouseClickedPanelActionEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedPanelActionEvent
        panelCrearCuenta.requestFocusInWindow();
    }//GEN-LAST:event_mouseClickedPanelActionEvent

    private void butonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCrearCuentaActionPerformed
        
        if(campoEmail.getText().equals("E-mail*"))
            labelErrorEmail.setText("Rellena el campo de E-mail");
        else if(!campoEmail.getText().matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$"))
            labelErrorEmail.setText("El correo está mal escrito");
        else
            labelErrorEmail.setText("                                                   ");
        
        if(campoUsuario.getText().equals("Usuario*"))
            labelErrorUsuario.setText("Rellena el campo de Usuario");
        else if(campoUsuario.getText().length() > 30)
            labelErrorUsuario.setText("El usuario tiene que ser menor de 30 caracteres");
        else
            labelErrorUsuario.setText("                                                   ");
        
        if(campoContraseña.getText().equals("Contraseña*"))
            labelErrorContraseña.setText("Rellena el campo de Contraseña");
        else if(!longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No cumple ningún requisito");
        else if(longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene números, ni mayúsculas, ni caracter especial");
        else if(longitudMinima(campoContraseña.getText()) && tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene mayúsculas, ni caracter especial");
        else if(longitudMinima(campoContraseña.getText()) && tieneNumero(campoContraseña.getText()) && tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene caracter especial");
        else if(!longitudMinima(campoContraseña.getText()) && tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene 8 caracteres, ni mayúsculas, ni caracter especial");
        else if(!longitudMinima(campoContraseña.getText()) && tieneNumero(campoContraseña.getText()) && tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene 8 caracteres, ni caracter especial");
        else if(!longitudMinima(campoContraseña.getText()) && tieneNumero(campoContraseña.getText()) && tieneMayuscula(campoContraseña.getText()) && tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene 8 caracteres");
        else if(!longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene 8 caracteres, ni números, ni caracter especial");
        else if(longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && tieneMayuscula(campoContraseña.getText()) && !tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene números, ni caracter especial");
        else if(longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && tieneMayuscula(campoContraseña.getText()) && tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene números");
        else if(longitudMinima(campoContraseña.getText()) && tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene mayúsculas");
        else if(!longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && tieneMayuscula(campoContraseña.getText()) && tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene 8 caracteres, ni números");
        else if(!longitudMinima(campoContraseña.getText()) && tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene 8 caracteres, ni mayúsculas");
        else if(longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene números, ni números");
        else if(!longitudMinima(campoContraseña.getText()) && !tieneNumero(campoContraseña.getText()) && !tieneMayuscula(campoContraseña.getText()) && tieneCaracterEspecial(campoContraseña.getText()))
            labelErrorContraseña.setText("No tiene 8 caracteres, ni números, ni mayúsculas");        
        else
            labelErrorContraseña.setText("                                                   ");
        
        if(campoCContraseña.getText().equals("Confirmar contraseña*"))
            labelErrorCContraseña.setText("Rellena el campo de confirmar contraseña");
        else if(!campoCContraseña.getText().equals(campoContraseña.getText()))
            labelErrorCContraseña.setText("No coincide la contraseña");
        else
            labelErrorCContraseña.setText("                                                   ");
        
        
        if(labelErrorEmail.getText().equals("                                                   ") &&
           labelErrorUsuario.getText().equals("                                                   ") &&
           labelErrorContraseña.getText().equals("                                                   ") &&
           labelErrorCContraseña.getText().equals("                                                   "))
        {
            EnviarCorreo.crearNuevaInstancia();
            EnviarCorreo.getInstancia().transfer_to_email(campoEmail.getText());
            InterfazConfirmarCuenta confirmar = new InterfazConfirmarCuenta();
        }
        
        
    }//GEN-LAST:event_butonCrearCuentaActionPerformed

    public void cuentaBD()
    {
        try {
            // Establecer la conexión a la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pcworld", "pcworld", "pcworld2024");

            // Verificar si el nombre de usuario ya existe en la tabla
            String queryUsuario = "SELECT * FROM datos_clientes WHERE Usuario = ?";
            PreparedStatement pstmtUsuario = cn.prepareStatement(queryUsuario);
            pstmtUsuario.setString(1, campoUsuario.getText().trim());
            ResultSet rsUsuario = pstmtUsuario.executeQuery();

            // Verificar si el correo electrónico ya existe en la tabla
            String queryCorreo = "SELECT * FROM datos_clientes WHERE `E-mail` = ?";
            PreparedStatement pstmtCorreo = cn.prepareStatement(queryCorreo);
            pstmtCorreo.setString(1, campoEmail.getText().trim());
            ResultSet rsCorreo = pstmtCorreo.executeQuery();

            if (rsUsuario.next()) 
            {
                // El nombre de usuario ya existe en la base de datos
                labelErrorUsuario.setText("Ya existe una cuenta con ese usuario");
                if(rsCorreo.next()) 
                {
                    labelErrorEmail.setText("El correo electrónico ya está en uso, prueba a iniciar sesión");
                }
            } 
            else if (rsCorreo.next()) 
            {
                // El correo electrónico ya existe en la base de datos
                labelErrorEmail.setText("El correo electrónico ya está en uso, prueba a iniciar sesión");
                if (rsUsuario.next()) 
                {
                    // El nombre de usuario ya existe en la base de datos
                    labelErrorUsuario.setText("Ya existe una cuenta con ese usuario");
                }
            } 
            else 
            {
                PreparedStatement pstmtInsertar = cn.prepareStatement("insert into datos_clientes values(?,?,?)");
                pstmtInsertar.setString(1, campoUsuario.getText().trim());
                pstmtInsertar.setString(2, campoEmail.getText().trim());
                pstmtInsertar.setString(3, campoContraseña.getText().trim());
                pstmtInsertar.executeUpdate();
                InterfazProducto.getInstancia().labelErrorCesta.setText(" ");
                InterfazProducto.getInstancia().labelErrorListaDeDeseos.setText(" ");
                InterfazPrincipal.getInstancia().cambiarTextoBotonCuenta(campoUsuario.getText().trim());
                
                // RESTO DE INTERFACES
                InterfazProducto.getInstancia().botonCuenta.setText(campoUsuario.getText().trim());
                InterfazMostrarProductos.getInstancia().botonCuenta.setText(campoUsuario.getText().trim());
                InterfazCesta.getInstancia().botonCuenta.setText(campoUsuario.getText().trim());
                InterfazListaDeseos.getInstancia().botonCuenta.setText(campoUsuario.getText().trim());
                InterfazMostrarProductos.getInstancia().botonCuenta.setText(campoUsuario.getText().trim());
                InterfazConfiguradorPcs.getInstancia().botonCuenta.setText(campoUsuario.getText().trim());
                this.dispose();
            }
        } catch(Exception e) {
            System.out.println("Error: " + e);
        }
    }
    
    private void labelVIniciarSesionActionPerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVIniciarSesionActionPerformed
        new InterfazLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelVIniciarSesionActionPerformed

    private void campoUsuariofocusLostEmailActionEvent(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuariofocusLostEmailActionEvent
        if(campoUsuario.getText().equals(""))
        {
            campoUsuario.setText("Usuario*");
        }
    }//GEN-LAST:event_campoUsuariofocusLostEmailActionEvent

    private void focusLostEmailActionEvent(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLostEmailActionEvent
        if(campoEmail.getText().equals(""))
        {
            campoEmail.setText("E-mail*");
        }
    }//GEN-LAST:event_focusLostEmailActionEvent

    private void campoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusGained
        if(campoEmail.getText().equals("E-mail*"))
        {
            campoEmail.setText("");
        }
    }//GEN-LAST:event_campoEmailFocusGained

    private void campoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusGained
        if(campoUsuario.getText().equals("Usuario*"))
        {
            campoUsuario.setText("");
        }
    }//GEN-LAST:event_campoUsuarioFocusGained

    private void campoContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContraseñaKeyReleased
        if(campoContraseña.getText().matches("^(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]).{8,}$"))
        {
            labelErrorContraseña.setText("                                                   ");
        }else if(!campoContraseña.getText().matches("^(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]).{8,}$"))
        {
            labelErrorContraseña.setText("Debe tener minimo 8 caracteres, 1 num, 1 may y 1 car.especial");
        }
    }//GEN-LAST:event_campoContraseñaKeyReleased

    private void campoContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaFocusLost
        if(campoContraseña.getText().equals(""))
        {
            campoContraseña.setText("Contraseña*");
        }
    }//GEN-LAST:event_campoContraseñaFocusLost

    private void campoContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoContraseñaFocusGained
        if(campoContraseña.getText().equals("Contraseña*"))
        {
            campoContraseña.setText("");
        }
    }//GEN-LAST:event_campoContraseñaFocusGained

    private void campoCContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCContraseñaFocusGained
        if(campoCContraseña.getText().equals("Confirmar contraseña*"))
        {
            campoCContraseña.setText("");
        }
    }//GEN-LAST:event_campoCContraseñaFocusGained

    private void campoCContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCContraseñaFocusLost
        if(campoCContraseña.getText().equals(""))
        {
            campoCContraseña.setText("Confirmar contraseña*");
        }
    }//GEN-LAST:event_campoCContraseñaFocusLost

    private void labelOjo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOjo1MouseClicked
        if(campoContraseña.getEchoChar() == '*')
        {
            labelOjo1.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "ojoNoVisible.png"));
            campoContraseña.setEchoChar((char) 0);
        }
        else
        {
            labelOjo1.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "ojoVisible.png"));
            campoContraseña.setEchoChar('*');
        }    
    }//GEN-LAST:event_labelOjo1MouseClicked

    private void labelOjo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOjo2MouseClicked
        if(campoCContraseña.getEchoChar() == '*')
        {
            labelOjo2.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "ojoNoVisible.png"));
            campoCContraseña.setEchoChar((char) 0);
        }
        else
        {
            labelOjo2.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "ojoVisible.png"));
            campoCContraseña.setEchoChar('*');
        }    
    }//GEN-LAST:event_labelOjo2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonCrearCuenta;
    private javax.swing.JPasswordField campoCContraseña;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelContraseña1;
    private javax.swing.JLabel labelCrearCuenta;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelErrorCContraseña;
    private javax.swing.JLabel labelErrorContraseña;
    private javax.swing.JLabel labelErrorEmail;
    private javax.swing.JLabel labelErrorUsuario;
    private javax.swing.JLabel labelOjo1;
    private javax.swing.JLabel labelOjo2;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelVIniciarSesion;
    private javax.swing.JPanel panelCrearCuenta;
    // End of variables declaration//GEN-END:variables
    private static InterfazCrearCuenta instancia;
}
