package src;

import java.awt.*;
import java.io.File;
import java.sql.*;
import java.util.*;
import javax.swing.*;

public class InterfazPanelFiltrosNombres extends javax.swing.JFrame 
{
    /**
     * Creates new form pruebaPanelFiltros
     */
    public InterfazPanelFiltrosNombres() 
    {
        initComponents();
    }
    
    public static InterfazPanelFiltrosNombres getInstancia()
    {
        if(instancia == null)
        {
            instancia = new InterfazPanelFiltrosNombres();
        }
        return instancia;
    }
    public static InterfazPanelFiltrosNombres crearNuevaInstancia() 
    {
        instancia = null;
        return getInstancia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        checkCPU = new javax.swing.JCheckBox();
        checkDiscoDuro = new javax.swing.JCheckBox();
        checkFuenteAlimentacion = new javax.swing.JCheckBox();
        checkRam = new javax.swing.JCheckBox();
        checkPlacaBase = new javax.swing.JCheckBox();
        checkRefrigeracion = new javax.swing.JCheckBox();
        checkTarjetaGrafica = new javax.swing.JCheckBox();
        checkPortatil = new javax.swing.JCheckBox();
        checkTorre = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(247, 224, 136));

        checkCPU.setBackground(new java.awt.Color(247, 224, 136));
        checkCPU.setText("CPU");
        checkCPU.setFocusable(false);
        checkCPU.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkCPU.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkCPUItemStateChanged(evt);
            }
        });

        checkDiscoDuro.setBackground(new java.awt.Color(247, 224, 136));
        checkDiscoDuro.setText("DISCO DURO");
        checkDiscoDuro.setFocusable(false);
        checkDiscoDuro.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkDiscoDuro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkDiscoDuroItemStateChanged(evt);
            }
        });

        checkFuenteAlimentacion.setBackground(new java.awt.Color(247, 224, 136));
        checkFuenteAlimentacion.setText("FUENTE DE ALIMENTACIÓN");
        checkFuenteAlimentacion.setFocusable(false);
        checkFuenteAlimentacion.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkFuenteAlimentacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkFuenteAlimentacionItemStateChanged(evt);
            }
        });

        checkRam.setBackground(new java.awt.Color(247, 224, 136));
        checkRam.setText("RAM");
        checkRam.setFocusable(false);
        checkRam.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkRam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkRamItemStateChanged(evt);
            }
        });

        checkPlacaBase.setBackground(new java.awt.Color(247, 224, 136));
        checkPlacaBase.setText("PLACA BASE");
        checkPlacaBase.setFocusable(false);
        checkPlacaBase.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkPlacaBase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkPlacaBaseItemStateChanged(evt);
            }
        });

        checkRefrigeracion.setBackground(new java.awt.Color(247, 224, 136));
        checkRefrigeracion.setText("REFRIGERACIÓN");
        checkRefrigeracion.setFocusable(false);
        checkRefrigeracion.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkRefrigeracion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkRefrigeracionItemStateChanged(evt);
            }
        });

        checkTarjetaGrafica.setBackground(new java.awt.Color(247, 224, 136));
        checkTarjetaGrafica.setText("TARJETA GRÁFICA");
        checkTarjetaGrafica.setFocusable(false);
        checkTarjetaGrafica.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkTarjetaGrafica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkTarjetaGraficaItemStateChanged(evt);
            }
        });

        checkPortatil.setBackground(new java.awt.Color(247, 224, 136));
        checkPortatil.setText("PORTÁTIL");
        checkPortatil.setFocusable(false);
        checkPortatil.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkPortatil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkPortatilItemStateChanged(evt);
            }
        });

        checkTorre.setBackground(new java.awt.Color(247, 224, 136));
        checkTorre.setText("TORRE");
        checkTorre.setFocusable(false);
        checkTorre.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
        checkTorre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkTorreItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(checkTorre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkPortatil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkDiscoDuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkRefrigeracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkTarjetaGrafica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkRam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkFuenteAlimentacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkPlacaBase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 142, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDiscoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRefrigeracion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTarjetaGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkFuenteAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPlacaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkCPUItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkCPUItemStateChanged
        if (checkCPU.isSelected()) 
        {
            checkCPU.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkCPU.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkCPUItemStateChanged

    private void checkDiscoDuroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkDiscoDuroItemStateChanged
        if (checkDiscoDuro.isSelected()) 
        {
            checkDiscoDuro.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkDiscoDuro.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkDiscoDuroItemStateChanged

    private void checkRamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkRamItemStateChanged
        if (checkRam.isSelected()) 
        {
            checkRam.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkRam.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkRamItemStateChanged

    private void checkRefrigeracionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkRefrigeracionItemStateChanged
        if (checkRefrigeracion.isSelected()) 
        {
            checkRefrigeracion.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkRefrigeracion.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkRefrigeracionItemStateChanged

    private void checkTarjetaGraficaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkTarjetaGraficaItemStateChanged
        if (checkTarjetaGrafica.isSelected()) 
        {
            checkTarjetaGrafica.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkTarjetaGrafica.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkTarjetaGraficaItemStateChanged

    private void checkFuenteAlimentacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkFuenteAlimentacionItemStateChanged
        if (checkFuenteAlimentacion.isSelected()) 
        {
            checkFuenteAlimentacion.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkFuenteAlimentacion.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkFuenteAlimentacionItemStateChanged

    private void checkPlacaBaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkPlacaBaseItemStateChanged
        if (checkPlacaBase.isSelected()) 
        {
            checkPlacaBase.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkPlacaBase.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkPlacaBaseItemStateChanged

    private void checkPortatilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkPortatilItemStateChanged
        if (checkPortatil.isSelected()) 
        {
            checkPortatil.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkPortatil.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkPortatilItemStateChanged

    private void checkTorreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkTorreItemStateChanged
        if (checkTorre.isSelected()) 
        {
            checkTorre.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "check.png"));
            buscarFiltros();
        } else 
        {
            checkTorre.setIcon(new javax.swing.ImageIcon("ImagenesDecoracion" + File.separator + "square.png"));
            buscarFiltros();
        }
    }//GEN-LAST:event_checkTorreItemStateChanged

    public void buscarFiltros() {
        InterfazMostrarProductos.getInstancia().panelProductos = null;
        InterfazMostrarProductos.getInstancia().panelProductos = new JPanel(new GridLayout(0,3, 20,38));
        InterfazMostrarProductos.getInstancia().panelProductos.setBackground(Color.WHITE);
        InterfazMostrarProductos.getInstancia().scrollPane.setViewportView(InterfazMostrarProductos.getInstancia().panelProductos);
        try {
                // Establecer la conexión a la base de datos
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pcworld", "pcworld", "pcworld2024");

                // Recopilar los nombres de las marcas seleccionadas
                ArrayList<String> tiposSeleccionados = new ArrayList<>();
                if (checkCPU.isSelected()) 
                    tiposSeleccionados.add("CPU");
                if (checkDiscoDuro.isSelected()) 
                    tiposSeleccionados.add("Disco duro");
                if (checkFuenteAlimentacion.isSelected()) 
                    tiposSeleccionados.add("Fuente alimentación");
                if (checkRam.isSelected()) 
                    tiposSeleccionados.add("Memoria RAM");
                if (checkPlacaBase.isSelected()) 
                    tiposSeleccionados.add("Placa base");
                if (checkRefrigeracion.isSelected()) 
                    tiposSeleccionados.add("Refrigeracion");
                if (checkTarjetaGrafica.isSelected()) 
                    tiposSeleccionados.add("Tarjeta Grafica");
                if (checkPortatil.isSelected()) 
                    tiposSeleccionados.add("Portatil");
                if (checkTorre.isSelected()) 
                    tiposSeleccionados.add("Torre");
                if(tiposSeleccionados.isEmpty())
                {
                    InterfazMostrarProductos.getInstancia().cargarProductosDesdeBD();
                }
                else{
                    // Construir la consulta SQL dinámica
                    StringBuilder consulta = new StringBuilder("SELECT * FROM productos WHERE IdNombre LIKE ? AND ( ");
                    for (int i = 0; i < tiposSeleccionados.size(); i++) {
                        consulta.append("tipoProducto = ?");
                        if (i < tiposSeleccionados.size() - 1) {
                            consulta.append(" OR ");
                        }
                    }
                    //consulta.append(")");
                    if(InterfazMostrarProductos.getInstancia().checkAscendente.isSelected())
                    {
                        consulta.append(") ORDER BY precioProducto ASC");
                    }else if(InterfazMostrarProductos.getInstancia().checkDescendente.isSelected())
                    {
                        consulta.append(") ORDER BY precioProducto DESC");
                    }else
                    {
                        consulta.append(")");
                    }
                    // Preparar la consulta
                    PreparedStatement pstmt = cn.prepareStatement(consulta.toString());
                    if(InterfazPrincipal.getInstancia().interfazActual.equals("InterfazPrincipal"))
                        pstmt.setString(1, "%" + InterfazPrincipal.getInstancia().campoBusqueda.getText() + "%");
                    else if(InterfazPrincipal.getInstancia().interfazActual.equals("InterfazProducto"))
                        pstmt.setString(1, "%" + InterfazProducto.getInstancia().campoBusqueda.getText() + "%");
                    else if(InterfazPrincipal.getInstancia().interfazActual.equals("InterfazCesta"))
                        pstmt.setString(1, "%" + InterfazCesta.getInstancia().campoBusqueda.getText() + "%");
                    else if(InterfazPrincipal.getInstancia().interfazActual.equals("InterfazListaDeseos"))
                        pstmt.setString(1, "%" + InterfazListaDeseos.getInstancia().campoBusqueda.getText() + "%");
                    else if(InterfazPrincipal.getInstancia().interfazActual.equals("InterfazMostrarProductos"))
                        pstmt.setString(1, "%" + InterfazMostrarProductos.getInstancia().campoBusqueda.getText() + "%");
                    else if(InterfazPrincipal.getInstancia().interfazActual.equals("InterfazCofiguradorPcs"))
                        pstmt.setString(1, "%" + InterfazConfiguradorPcs.getInstancia().campoBusqueda.getText() + "%");

                    // Establecer los parámetros de la consulta
                    for (int i = 0; i < tiposSeleccionados.size(); i++) {
                        pstmt.setString(i + 2, tiposSeleccionados.get(i));
                    }

                    // Ejecutar la consulta
                    ResultSet rs = pstmt.executeQuery();

                    // Procesar los resultados
                    while (rs.next())
                    {
                        cargarProductosDesdeBD(rs.getString("IdNombre"));
                    }
                }
                cn.close();
            } catch(Exception e) {
                System.out.println("Error: " + e);
            }
        InterfazMostrarProductos.getInstancia().scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        InterfazMostrarProductos.getInstancia().scrollPane.setViewportView(InterfazMostrarProductos.getInstancia().panelProductos);
        InterfazMostrarProductos.getInstancia().panelPrincipal.requestFocusInWindow();
        // Obtener la vista del JViewport
        JViewport viewport = InterfazMostrarProductos.getInstancia().scrollPane.getViewport();

        // Establecer la posición de la vista en la parte superior
        SwingUtilities.invokeLater(() -> {
            viewport.setViewPosition(new Point(0, 0));
        });
    }
    
    public void cargarProductosDesdeBD(String nombre)
    {
        try {
            String rutaImagenPortada = "Imagenes" + File.separator + "Portada" + File.separator;
            Connection cn = InterfazMostrarProductos.getInstancia().conectarBD();

            ResultSet rsProducto;
            rsProducto = InterfazMostrarProductos.getInstancia().cargarProductosSegunFiltroMarcaNombre(cn, nombre);

            
            while (rsProducto.next())
            {
                Producto producto = InterfazMostrarProductos.getInstancia().crearProductoDesdeResultSet(rsProducto, rutaImagenPortada);
                InterfazMostrarProductos.getInstancia().actualizarValoresSliders((int) producto.getPrecio());
                InterfazMostrarProductos.getInstancia().crearPanelYActualizarInterfaz(producto);
            }

            cn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox checkCPU;
    public javax.swing.JCheckBox checkDiscoDuro;
    public javax.swing.JCheckBox checkFuenteAlimentacion;
    public javax.swing.JCheckBox checkPlacaBase;
    public javax.swing.JCheckBox checkPortatil;
    public javax.swing.JCheckBox checkRam;
    public javax.swing.JCheckBox checkRefrigeracion;
    public javax.swing.JCheckBox checkTarjetaGrafica;
    public javax.swing.JCheckBox checkTorre;
    public javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
    private static InterfazPanelFiltrosNombres instancia;
}
