-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 06-05-2024 a las 16:18:54
-- Versión del servidor: 5.6.26
-- Versión de PHP: 5.5.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- -----------------------------------------------------
-- Borrar la DATABASE pcworld si existe
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `pcworld`;
-- -----------------------------------------------------
-- Crear la DATABASE pcworld si no existe
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `pcworld` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `pcworld`;
-- -----------------------------------------------------
-- Crear USUARIO pcworld y permisos a pcworld
-- -----------------------------------------------------
CREATE USER 'pcworld'@'localhost' IDENTIFIED BY 'pcworld2024';
GRANT ALL PRIVILEGES ON `pcworld`.* TO 'pcworld'@'localhost';


-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `atencion_cliente`
--

CREATE TABLE IF NOT EXISTS `atencion_cliente` (
  `Usuario` varchar(20) NOT NULL,
  `Destino` varchar(20) NOT NULL,
  `Mensaje` varchar(1000) NOT NULL,
  `Fecha` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `cesta`
--

CREATE TABLE IF NOT EXISTS `cesta` (
  `IdCliente` varchar(20) NOT NULL,
  `IdProducto` varchar(150) NOT NULL,
  `cantidadProducto` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `datos_clientes`
--

CREATE TABLE IF NOT EXISTS `datos_clientes` (
  `Usuario` varchar(20) NOT NULL,
  `E-mail` varchar(30) NOT NULL,
  `Contraseña` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

--
-- Volcado de datos para la tabla `datos_clientes`
--

INSERT INTO `datos_clientes` (`Usuario`, `E-mail`, `Contraseña`) VALUES
('Admin', 'Admin', 'Admin');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `lista_deseos`
--

CREATE TABLE IF NOT EXISTS `lista_deseos` (
  `IdCliente` varchar(20) NOT NULL,
  `IdProducto` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pedidos`
--

CREATE TABLE IF NOT EXISTS `pedidos` (
  `IdPedido` varchar(6) NOT NULL,
  `Usuario` varchar(20) NOT NULL,
  `Fecha` varchar(20) NOT NULL,
  `nombreProducto` varchar(150) NOT NULL,
  `cantidadProducto` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `productos`
--

CREATE TABLE IF NOT EXISTS `productos` (
  `IdNombre` varchar(150) NOT NULL,
  `tipoProducto` varchar(30) NOT NULL,
  `precioProducto` decimal(10,2) NOT NULL,
  `stockProducto` int(5) NOT NULL,
  `descripcionProducto` varchar(2000) NOT NULL,
  `imagen1Producto` varchar(160) NOT NULL,
  `imagen2Producto` varchar(160) NOT NULL,
  `oculto` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `productos`
--

INSERT INTO `productos` (`IdNombre`, `tipoProducto`, `precioProducto`, `stockProducto`, `descripcionProducto`, `imagen1Producto`, `imagen2Producto`, `oculto`) VALUES
('Acer Aspire 1 A114-61-S94P Qualcomm Snapdragon SC7180/8GB/128GB eMMC/14"', 'Portatil', '229.00', 6, 'El Acer Aspire 1 ofrece funcionalidad práctica en cualquier lugar a un bajo costo. Con un diseño "Pearl White", el procesador Qualcomm® Snapdragon™ 7c, la batería de 20 horas y la tecnología 4G LTE hacen de este dispositivo una opción versátil y preparada para los desafíos diarios. Características: Batería duradera de hasta 20 horas. Portabilidad gracias al procesador Snapdragon™ 7c de bajo consumo. Conectividad con puertos USB Type-C y USB 3.2 Type-A Gen 1. Especificaciones de Acer Aspire 1 Qualcomm: Procesador Qualcomm Snapdragon SC7180 2.4 GHz. 8 GB de RAM DDR4X. Almacenamiento eMMC de 128 GB. Pantalla LCD LED de 14" HD.Controlador gráfico Qualcomm® Adreno 618. Conectividad Wi-Fi 802.11ac y Bluetooth 5.0. Batería de 48Wh. Puertos USB 3.2 Gen. 2 tipo C y USB 3.2 de segunda generación. Sistema operativo Windows 11 Home 64 Bits. Dimensiones: 328 x 236 x 18,90 mm. Peso: 1,5 kg.Color: Blanco.', 'Portatiles/AcerAspire/Im1.jpg', 'Portatiles/AcerAspire/Im2.jpg', 0),
('Acer Nitro V 15 ANV15-51-51PQ Intel Core i5-13420H/16GB/1TB SSD/RTX 3050/15.6"', 'Portatil', '729.00', 10, 'El Acer Nitro V 15 lleva tus aventuras gaming a otro nivel, combinando potencia y estilo en un portátil excepcional. Equipado con un procesador Intel® Core™ i5-13420H de 13.ª generación, ofrece un rendimiento superior con almacenamiento y RAM DDR5 de alta velocidad. Su pantalla Full HD de 15,6 pulgadas con frecuencia de actualización de hasta 144Hz te sumerge en un mundo de gaming vibrante. Los innovadores ventiladores mantienen la temperatura bajo control incluso en las batallas más intensas. Con Wi-Fi 6, Ethernet Gigabit y la aplicación NitroSense, estarás siempre listo para la acción. Especificaciones: Procesador Intel® Core™ i5- 13420H, 16GB de RAM DDR5 (ampliable hasta 32GB), 1024GB PCIe NVMe SSD (ampliable hasta 2TB), tarjeta gráfica NVIDIA® GeForce RTX™ 3050 6G-GDDR6, entre otros. Sistema operativo: Sin sistema operativo. Dimensiones: 362.3 x 239.89 x 22.9/26.9 mm. Peso: 2,1 kg. Color: Negro.', 'Portatiles/AcerNitro/Im1.jpg', 'Portatiles/AcerNitro/Im2.jpg', 0),
('Acer Predator Triton 500 SE PT516-51s-75K6 Intel Core i7-11800H/32GB/1TB SSD/RTX 3080/16"', 'Portatil', '920.05', 10, 'El Triton 500 SE es un portátil gaming delgado y elegante diseñado para multitarea, rendimiento extremo y creatividad. Con un procesador Intel Core i7-11800H, 32GB de memoria DDR4, y almacenamiento SSD PCIe NVMe de 1024GB, ofrece un potente rendimiento. La pantalla de 16" WQXGA con una frecuencia de actualización de 165Hz y la tarjeta gráfica NVIDIA GeForce RTX 3080 garantizan una experiencia visual inmersiva. Con conectividad Bluetooth 5.1, Wi-Fi 6, y Thunderbolt 4. Incluye Windows 11 Home, cámara HD, micrófono, y lector de huellas. Dimensiones: 358.5 x 262.4 x 19.9 mm. Peso: 2.4 kg. Color: Gris. Incluye 1 mes de Xbox Game Pass Ultimate.', 'Portatiles/AcerPredator/Im1.jpg', 'Portatiles/AcerPredator/Im2.jpg', 0),
('Acer Predator Vesta II RGB DDR5 6000MHz 32GB 2x16GB CL30', 'Memoria RAM', '129.99', 6, 'La memoria Predator Vesta II DDR5 lleva el rendimiento de juego y computación a nuevas alturas con su velocidad ultrarrápida, diseño elegante y iluminación RGB personalizable. Con componentes de calidad y overclocking fácil, es ideal para cualquier tarea intensiva en la computadora. Sus características incluyen iluminación RGB brillante, ICS clasificados a mano para tiempos ultrabajos, compatibilidad con placas base y CPU de primer nivel, y ECC integrado para la corrección de errores. Además, cuenta con un elegante disipador de calor metálico con sensor de temperatura integrado y PMIC programable para mejorar la estabilidad del sistema. Con Intel XMP 3.0 para overclocking de un clic y una garantía limitada de por vida, la Predator Vesta II es una opción líder en rendimiento y estilo.', 'MemoriaRAM/AcerPredator/Im1.jpg', 'MemoriaRAM/AcerPredator/Im2.jpg', 0),
('Adata XPG Lancer DDR5 6400MHz 64 GB2x32GB CL32', 'Memoria RAM', '364.31', 9, 'El ADATA AX5U6400C3232G-DCLABK es un kit de dos módulos de memoria DDR5-6400 de 32 GB (PC5-51200) de la serie XPG Lancer, con una capacidad total de 64 GB. Los DIMM de 288 pines admiten una sincronización de 32-39-39 a 6400 MHz y requieren un voltaje de 1,4 voltios. Cuentan con PMIC y ECC para mejorar el rendimiento y la estabilidad, y son compatibles con Intel XMP 3.0 y AMD EXPO para overclocking. Especificaciones: SDRAM DDR5, color negro, capacidad de 64 GB (2 x 32 GB), diseño DIMM, perfiles INTEL XMP (Versión 3.0) y AMD EXPO, voltaje de 1,4 voltios, estándar DDR5-6400 (PC5-51200), reloj físico de 3200 MHz, y sincronizaciones con latencia CAS (CL) de 32, RAS-al-CAS Delay (tRCD) de 39, y Tiempo RAS Precharge (tRP) de 39.', 'MemoriaRAM/AdataXPG/Im1.jpg', 'MemoriaRAM/AdataXPG/Im2.jpg', 0),
('Alurin Go Intel Pentium N4200/4GB/128GB SSD/14.1"', 'Portatil', '309.00', 9, 'El portátil Alurin GO N4200 es el aliado perfecto para el trabajo y el entretenimiento, con un diseño ultrafino y ligero que te permite llevarlo a cualquier lugar. Equipado con un potente procesador Intel® Pentium™ N4200, gran almacenamiento SSD y alta capacidad de RAM. Su batería de 5000mAh ofrece hasta 7 horas de uso, y su pantalla de 14.1" garantiza una visualización detallada. Además, cuenta con excelentes opciones de conectividad, incluyendo puertos USB, miniHDMI y lector de tarjetas MicroSD. Viene con Windows 10 instalado y ofrece fiabilidad y robustez. Especificaciones: Procesador Intel Pentium N4200, 4GB de RAM DDR4, 128GB SSD + puerto SATA 2.5", pantalla HD de 14.1", WiFi, Bluetooth, cámara integrada, batería de 5000mAh, y varias conexiones. Sistema operativo: Windows 10 S. Dimensiones: 330 x 220 x 23 mm. Peso: 1.25 kg. Color: Gris.', 'Portatiles/AlurinGo/Im1.jpg', 'Portatiles/AlurinGo/Im2.jpg', 0),
('Alurin Zenith Intel Core i5-1235U/16GB/500GB SSD/15.6" + Windows 11 Home', 'Portatil', '739.00', 8, 'El portátil Alurin Zenith combina diseño elegante con resistencia. Su batería de 11.4V/55Wh garantiza movilidad sin límites. La webcam de 2MP y 4 altavoces ofrecen comunicación clara. El lector de huellas proporciona seguridad adicional. Viene con Windows 11 preinstalado y ofrece conectividad ultrarrápida con Wifi 6 y Bluetooth 5.2. Desde Thunderbolt 4 hasta teclado retroiluminado, cada función y puerto ha sido seleccionado para ofrecerte la mejor experiencia. Especificaciones: Procesador Intel Core i5-1235U, 16GB RAM DDR4, 500GB SSD M.2 PCIe. Controlador gráfico Intel Iris Xe Graphics. Pantalla 15.6” FHD IPS. Teclado retroiluminado. Incluye micrófono, cámara integrada y lector de huellas. Con Windows 11. Conectividad Wifi 6, Bluetooth 5.2. Conexiones: RJ45, 1 USB A 3.2, 2 Thunderbolt 4, 1 HDMI, conector de auriculares/micrófono, lector de tarjetas MicroSD. Dimensiones: 360 x 236 x 26 mm. Peso: 1.75 Kg. Color: Plata.', 'Portatiles/AlurinZenith/Im1.jpg', 'Portatiles/AlurinZenith/Im2.jpg', 0),
('AMD Radeon PRO W7800 32GB GDDR6', 'Tarjeta Grafica', '2891.19', 8, 'El producto Hellhound ofrece una experiencia de juego confiable y elegante, con características como la tecnología de super resolución AMD FidelityFX™ para mejorar la calidad de imagen y el rendimiento, optimización para Windows 11, arquitectura AMD RDNA™ 3 con hardware de trazado de rayos, y tecnología AMD FreeSync™ para una experiencia de juego sin tartamudeos. Las especificaciones de la PowerColor HELLHOUND AMD Radeon RX 7900 XTX incluyen un procesador Radeon RX 7900 XTX con 24 GB de memoria GDDR6, interfaz PCI Express 4.0, y características de diseño como iluminación LED.', 'TarjetasGraficas/AMDRadeonPRO/Im1.jpg', 'TarjetasGraficas/AMDRadeonPRO/Im2.jpg', 0),
('AMD Ryzen 5 5600X 3.7GHz', 'CPU', '149.90', 10, 'Juega con lo mejor: Seis núcleos para una experiencia de juego excepcional. Características: · Tecnología AMD StoreMI: Combina la velocidad de SSD con la capacidad del disco duro en una unidad fácil de administrar.  · Utilidad AMD Ryzen™ Master: Software de overclocking potente y fácil de usar para procesadores AMD Ryzen™. · AMD Ryzen™ VR-Ready Premium: Procesadores de alto rendimiento para una experiencia de realidad virtual premium.  Especificaciones: 6 núcleos y 12 hilos con velocidades de hasta 4.6GHz, caché L2 de 3MB y caché L3 de 32MB, desbloqueados para overclocking, tecnología de proceso TSMC 7nm FinFET, compatible con PCIe 4.0 y memoria DDR4 de hasta 3200MHz e incluye solución térmica Wraith Stealth con un TDP de 65W.', 'CPU/AMDRyzen5/Im1.jpg', 'CPU/AMDRyzen5/Im2.jpg', 0),
('AMD Ryzen 7 7800X3D 4.2 GHz/5 GHz', 'CPU', '390.00', 10, 'Procesador AMD Ryzen™ 7 7800X3D: Diseñado para los entusiastas de los juegos, este procesador líder en la industria cuenta con la innovadora tecnología AMD 3D V-Cache™, ofreciendo un rendimiento excepcional para tus sesiones de juego. Con 8 núcleos y 16 hilos de ejecución, una frecuencia base de 4,2 GHz y una impresionante frecuencia turbo de 5 GHz, este procesador garantiza un rendimiento potente y una baja latencia para una experiencia de juego sin igual. Además, cuenta con gráficos AMD Radeon incorporados y es compatible con memoria DDR5-SDRAM de alta velocidad. ', 'CPU/AMDRyzen7/Im1.jpg', 'CPU/AMDRyzen7/Im2.jpg', 0),
('AMD Ryzen Threadripper 7960X 4.2/5.3GHz Box', 'CPU', '1925.81', 9, 'Los procesadores Ryzen Threadripper 7960X de AMD ofrecen tecnologías AMD PRO que proporcionan funciones de seguridad, herramientas de manejabilidad y estabilidad empresarial. Estas características simplifican la implementación, creación de imágenes y administración de flotas. La flexibilidad incluye estándares abiertos y compatibilidad inalámbrica para múltiples perfiles DASH. La implementación es fluida con tecnologías de configuraciones basadas en la nube como Windows Autopilot. La administración es escalable con compatibilidad para manejabilidad fuera de banda y dentro de banda, como Microsoft Endpoint Manager.  El procesador AMD Ryzen Threadripper 7960X tiene 24 núcleos, 48 hilos, frecuencia base de 4,2 GHz y turbo de 5,3 GHz, con 128 MB de caché L3 y TDP de 350 W. Es compatible con memoria DDR5-SDRAM en cuatro canales y PCI Express 5.0. Los sistemas operativos compatibles incluyen Windows 11 x64, RHEL x86 64-bit y Ubuntu x86 64-bit.', 'CPU/AMDRyzenThreadripper7960X/Im1.jpg', 'CPU/AMDRyzenThreadripper7960X/Im2.jpg', 0),
('AMD Ryzen Threadripper PRO 5955WX 4GHz/4.5GHz', 'CPU', '1601.96', 8, 'Los procesadores Ryzen Threadripper PRO 5000 WX-Series combinan el rendimiento de la arquitectura "Zen 3" con funciones de seguridad empresarial y escalabilidad de AMD PRO. Con frecuencias más altas y una arquitectura de caché L3 mejorada, permiten hacer frente a cargas de trabajo exigentes. La arquitectura "Zen 3" ofrece un rediseño integral con más de 20 cambios fundamentales, incluido un mayor IPC y menor latencia. Estas mejoras proporcionan un rendimiento excepcional en juegos y tareas sensibles a la latencia. El procesador AMD Ryzen Threadripper PRO 5955WX tiene 16 núcleos, 32 hilos, frecuencia base de 4 GHz y turbo de 4,5 GHz, con 64 MB de caché L3 y un TDP de 280 W. Es compatible con memoria DDR4- SDRAM en un octa-channel. No tiene gráficos integrados. Soporta PCI Express 4.0 y sistemas operativos Windows 11/10 x64.', 'CPU/AMDRyzenThreadripperPRO/Im1.jpg', 'CPU/AMDRyzenThreadripperPRO/Im2.jpg', 0),
('ASUS Chromebook CX1400CKA-EK0138 Intel Celeron N4500/8GB/64GB eMMC/14"', 'Portatil', '386.99', 9, 'El ASUS Chromebook CX1 es moderno, elegante y ultraportátil, ideal para usuarios móviles. Con un chasis ligero de 1,45 kg y resistente a los golpes y caídas, es perfecto para viajar. Equipado con un procesador Intel® de dos núcleos, ofrece un excelente rendimiento. Su pantalla antirreflejos de 14 pulgadas y su bisagra de 180º fomentan la productividad. El teclado ergonómico y la batería de hasta 12 horas de autonomía garantizan comodidad y productividad durante todo el día. Además, cuenta con actualizaciones automáticas, protección antivirus y acceso a Google Play. Las conexiones USB-C® y USB 3.2 facilitan la conectividad. Especificaciones: Procesador Intel Celeron N4500, 8GB de RAM LPDDR4, 64GB de almacenamiento eMMC, pantalla Full HD de 14", Wi-Fi 6 y Bluetooth 5.1. Sistema operativo ChromeOS. Dimensiones: 326,5 x 228,7 x 18,7 mm. Peso: 1,45 kg. Color: Plata.', 'Portatiles/AsusChromebook/Im1.jpg', 'Portatiles/AsusChromebook/Im2.jpg', 0),
('ASUS Pro WS TRX50-SAGE WIFI', 'Placa base', '965.70', 9, 'La placa base Pro WS TRX50-SAGE WIFI de ASUS es ideal para creación de contenido, desarrollo de software y aprendizaje automático. Con 36 etapas de potencia, soporta procesadores AMD Ryzen Threadripper™ PRO 7000 WX-series y AMD Ryzen Threadripper™ 7000 series, hasta 1 TB de memoria DDR5, y múltiples tarjetas gráficas. Ofrece conectividad ultrarrápida con PCIe® 5.0, LAN de 10 Gb y 2,5 Gb, y puertos USB de 20 Gbps. Incluye gestión remota IPMI de nivel de servidor y es estable y confiable, validada para una amplia compatibilidad. Especificaciones: Socket sTR5, soporte DDR5-SDRAM, hasta 7 unidades de almacenamiento, RAID 0, 1, 5, 10, y Wi-Fi 7 y Bluetooth 5.4 integrados. El factor de forma es SSI CEB, compatible con Windows 10 y 11. Ranuras de expansión: 2 PCIe x16 (Gen 4.x), 3 PCIe x16 (Gen 5.x), y 3 ranuras M.2 (M). BIOS UEFI AMI con botón de limpieza CMOS. Empaquetado: 320 mm x 380 mm x 100 mm, 4,85 kg. Dimensiones: 305 mm x 280 mm. Incluye cables PCIe y SATA. Peso: 2,53 kg.', 'PlacasBases/ASUSPro/Im1.jpg', 'PlacasBases/ASUSPro/Im2.jpg', 0),
('ASUS ROG CROSSHAIR X670E HERO', 'Placa base', '669.00', 1, 'El ROG Crosshair X670E Hero de ASUS ofrece una solución completa para potenciar construcciones con procesadores AMD Ryzen™ 7000 Series. Con una potencia de dieciocho etapas 110A, overclocking robusto y velocidades DDR5 de campeonato. Su diseño térmico y conectividad avanzada lo hacen ideal para construcciones de alto rendimiento. Ofrece herramientas de optimización flexibles y una iluminación personalizable con Polymo Lighting. Especificaciones: Soporte para procesadores AMD Ryzen™ 7000 Series, chipset AMD X670, memoria DDR5 hasta 6400+(OC) MHz, ranuras PCIe 5.0 y 4.0, almacenamiento M.2 y SATA, Ethernet Intel® de 2.5Gb, Wi-Fi 6E, USB de alta velocidad y audio SupremeFX 7.1.', 'PlacasBases/ASUSROGCROSSHAIR/Im1.jpg', 'PlacasBases/ASUSROGCROSSHAIR/Im2.jpg', 0),
('ASUS ROG Ryujin III 360 ARGB EVA-02 Kit de Refrigeración Líquida', 'Refrigeracion', '578.17', 10, 'El ROG Ryujin III 360 ARGB EVA-02 Edition es un enfriador de CPU líquido todo en uno que presenta una pantalla LCD de 3,5", bomba Asetek de 8.ª generación, ventilador integrado en la bomba y ventiladores de radiador ARGB magnéticos ROG de 120 mm conectables en cadena. Se centra en el proyecto EVANGELION, con un diseño inspirado en EVA-02 y Asuka. La pantalla LCD muestra animaciones GIF temáticas de Asuka y EVA-02. Con una bomba Asetek de última generación, ventilador integrado mejorado y ventiladores magnéticos ARGB, ofrece un rendimiento óptimo de enfriamiento. Además, permite el control completo a través de Armory Crate y viene con una licencia AIDA 64 gratuita de un año para monitoreo avanzado del sistema', 'Refrigeraciones/ASUSROG/Im1.jpg', 'Refrigeraciones/ASUSROG/Im2.jpg', 0),
('ASUS ROG Strix 1000W Gold Aura Edition 80 Plus Gold Modular', 'Fuente alimentación', '291.69', 10, 'La fuente de alimentación ROG Strix 1000W Gold Aura Edition de ASUS ofrece una combinación de componentes premium, refrigeración eficiente y una llamativa iluminación RGB. Con un diseño de chasis de aluminio resistente, disipadores de calor ROG y tecnología de ventilador axial, garantiza un rendimiento óptimo y una operación silenciosa. Además, cuenta con certificación 80 Plus Gold, protecciones de alta resistencia y es compatible con ATX 3.0. Con Aura Sync integrado, ofrece una estética impresionante y una garantía global de 10 años.', 'FuentesAlimentacion/ASUSROGStrix/Im1.jpg', 'FuentesAlimentacion/ASUSROGStrix/Im2.jpg', 0),
('ASUS ROG Strix GeForce RTX 4090 24GB GDDR6X DLSS3', 'Tarjeta Grafica', '2863.98', 8, 'La ROG Strix GeForce RTX® 4090 redefine el estándar de rendimiento. Con la arquitectura NVIDIA Ada Lovelace, esta GPU ofrece un salto impresionante en rendimiento y gráficos, con tecnología de IA para mundos virtuales realistas y juegos ultra fluidos. El trazado de rayos alcanza nuevos niveles de realismo, mientras que DLSS 3 impulsa el rendimiento con IA. NVIDIA Reflex garantiza la latencia más baja para una ventaja competitiva. Especificaciones: NVIDIA® GeForce RTX® 4090, 24 GB GDDR6X, 1 x 16-pin, 2 x HDMI 2.1a, 3 x DisplayPort 1.4a, HDCP 2.3, resolución máxima 7680 x 4320, compatible con PCIe 4.0, PSU recomendada 1000 W. Dimensiones: 357.6 x 149.3 x 70.1mm, peso 2.503 kg. Características adicionales incluyen un paquete de accesorios y software ASUS GPU Tweak III', 'TarjetasGraficas/ASUS4090/Im1.jpg', 'TarjetasGraficas/ASUS4090/Im2.jpg', 0),
('ASUS ROG STRIX Z790-F GAMING WIFI II', 'Placa base', '486.99', 6, 'El ROG Strix Z790-F II de ASUS ofrece una solución completa para potenciar cualquier construcción. Con la tecnología Q-Antenna, conectar una antena WiFi es rápido y fácil. La entrega de energía robusta, almacenamiento rápido y memoria DDR5, junto con refrigeración integral, aseguran un rendimiento óptimo. El overclocking de IA ajusta de manera inteligente la CPU y la refrigeración para alcanzar la configuración óptima. Con Wi-Fi 7, Ethernet Intel® de 2,5G, y Aura Sync RGB, ofrece conectividad líder y estilo personalizable. Además, cuenta con una amplia gama de utilidades de software exclusivas de ROG para configuración avanzada del sistema.  Especificaciones: Soporte para procesadores Intel® Core™ de 14.ª y 13.ª generación, chipset Intel® Z790, memoria DDR5 hasta 8000+(OC) MHz, ranuras de expansión PCIe 5.0 y 4.0, almacenamiento M.2 y SATA, Ethernet Intel® de 2,5G, Wi-Fi 7, USB de alta velocidad, y audio SupremeFX 5.1.', 'PlacasBases/ASUSROGSTRIX/Im1.jpg', 'PlacasBases/ASUSROGSTRIX/Im2.jpg', 0),
('ASUS ROG Thor 1600T Gaming 1600W 80 Plus Titanium Modular', 'Fuente alimentación', '749.26', 10, 'La ROG Thor 1600W Titanium es una fuente de alimentación potente para equipos de alto rendimiento, con transistores de nitruro de galio, control digital y condensadores de baja ESR. Ofrece eficiencia energética, disipadores de calor integrados para una mejor refrigeración, y un ventilador PWM de 135 mm para un funcionamiento silencioso. Certificada como 80 PLUS Titanium, cuenta con protecciones avanzadas y una clasificación de ruido Lambda A++. Incluye cables con funda y tiene un diseño elegante en negro y plata', 'FuentesAlimentacion/ASUSROGThor/Im1.jpg', 'FuentesAlimentacion/ASUSROGThor/Im2.jpg', 0),
('ASUS TUF GAMING B760 PLUS WIFI D4', 'Placa base', '163.99', 10, 'La placa base ASUS TUF GAMING B760-PLUS WIFI D4 es compatible con procesadores híbridos Intel Core de 12ª y 13ª generación, DDR4 hasta 5333 MHz (OC), 3 ranuras M.2 PCIe 4.0 y 4 puertos SATA 6 Gbps. Incorpora ASUS TUF PROTECTION con DIGI+ VRM, LAN de 2,5 GbE, Wi-Fi 6 AX/Bluetooth 5.2, y puerto USB 3.2 Tipo C. Soporta ventiladores Aura Sync y ARGB. Especificaciones: CPU Intel Socket LGA1700, chipset Intel B760, memoria DDR4, ranuras PCIe 5.0 x16 y PCIe 3.0 x16, LAN Realtek 2.5Gb Ethernet, Wi-Fi 6, y puertos USB 3.2 Gen 2x2, 3.2 Gen 2, y 3.2 Gen 1. Incluye audio Realtek 7.1 Surround Sound High Definition, ASUS TUF PROTECTION, ASUS Q-Design, ASUS Thermal Solution, ASUS EZ DIY, y software exclusivo ASUS. Viene en formato ATX. ', 'PlacasBases/ASUSTUFGAMING/Im1.jpg', 'PlacasBases/ASUSTUFGAMING/Im2.jpg', 0),
('ASUS TUF Gaming F15 FX507ZC4-HN002 Intel Core i7-12700H/16GB/512GB SSD/RTX 3050/15.6"', 'Portatil', '799.00', 10, 'Características: Procesador Intel® Core™ i7 de 12.ª generación y GPU para portátiles GeForce RTX™ serie 30Sistema de refrigeración Arc Flow Fans™ con múltiples conductos de escape y tubos de calor. Chasis más compacto, teclado robusto y panel táctil más grande. Pantalla de hasta QHD 165 Hz o FHD 300 Hz con Adaptive-Sync y relación pantalla-cuerpo del 80%Compatibilidad con Thunderbolt™ 4 y USB tipo C, memoria RAM DDR5-4800 MHz y batería de hasta 90 Wh. Cumple con estándares MIL-STD-810H de resistencia a golpes y vibraciones. Especificaciones Asus TUF Gaming F15Procesador Intel Core i7-12700HMemoria RAM 16GB DDR4Almacenamiento 512GB SSD M.2 NV. Me PCIePantalla Full HD 15.6" 144Hz IPSGPU NVIDIA GeForce RTX 3050 4GB GDDR6Conectividad Wi-Fi 6 y Bluetooth 5.2Teclado Retroiluminado RGB. Batería de 56 Wh. Diversas conexiones, incluyendo HDMI, Thunderbolt™ 4 y USB 3.2 Gen 2Sistema operativo Free DOS. Dimensiones: 35.4 x 25.1 x 2.24 ~ 2.49 cm Peso: 2.2 kg Color: Negro', 'Portatiles/ASUSTUFGaming/Im1.jpg', 'Portatiles/ASUSTUFGaming/Im2.jpg', 0),
('Biostar A68N-2100K', 'Placa base', '55.81', 1, 'La placa base Biostar A68N-2100K cuenta con un procesador integrado AMD E1-6010 APU con gráficos Radeon R2. Admite hasta 16 GB de memoria DDR3/DDR3L y dispone de conexiones HDMI y USB 3.2 Gen1. Incluye características como audio de alta definición, salida S/P DIF, HDMI 4K2K, soporte DX 11.1, SATA 3 6Gbps, USB 3.2 Gen1 Tipo-A, capacitadores 100% sólidos, BIOS UEFI y BIO-Flasher para actualización de BIOS. Especificaciones: procesador AMD E1-6010, 2 núcleles, soporte para DDR3/DDR3L, interfaces SATA III, gráficos HDCP, y factor de forma mini ITX. Compatible con Windows 10, Windows 7 y Windows 8.1', 'PlacasBases/Biostar/Im1.jpg', 'PlacasBases/Biostar/Im2.jpg', 0),
('Biostar GeForce 210 1GB DDR3 Low Profile', 'Tarjeta Grafica', '48.18', 6, 'La tarjeta gráfica Nvidia GeForce 210 de Biostar cuenta con 1GB de memoria DDR3 y un perfil bajo. Presenta una GPU NVIDIA GeForce 210 y una memoria DDR3 de 1024 MB de alta velocidad. Con salidas VGA, DVI y HDMI, ofrece una amplia compatibilidad de visualización. Se conecta a través de la interfaz de bus PCI Express 2.0 x16. Esta tarjeta es compatible con la tecnología NVIDIA PureVideo HD y DirectX 10.1. Con un procesador gráfico GeForce 210 y una frecuencia de procesador de 589 MHz, admite una resolución máxima de 2048 x 1536 píxeles. Su capacidad de memoria de adaptador gráfico es de 1 GB, con una velocidad de memoria del reloj de 1000 MHz. Además, cuenta con un puerto HDMI, un puerto VGA y un puerto DVI. ', 'TarjetasGraficas/BiostarGeForce/Im1.jpg', 'TarjetasGraficas/BiostarGeForce/Im2.jpg', 0),
('Cooler Master Wraith Ripper Ventilador CPU', 'Refrigeracion', '195.99', 10, 'La Armadura de Espectro del Cooler Master Wraith Ripper está diseñada para optimizar el flujo de aire y reducir los puntos de calor, iluminada por LED RGB para una personalización completa. Con cobertura total para 32 núcleos/64 hilos de AMD Ryzen Threadripper, su disipador de calor de doble torre y 7 tubos de calor distribuyen uniformemente el calor para un enfriamiento eficiente. La instalación es más fácil gracias al diseño exclusivo de montaje Threadripper. Incluye una utilidad de control de iluminación RGB para una experiencia personalizada.', 'Refrigeraciones/CoolerMaster/Im1.jpg', 'Refrigeraciones/CoolerMaster/Im2.jpg', 0),
('Corsair iCUE H150i ELITE LCD XT Kit de Refrigeración Líquida 360mm Negro', 'Refrigeracion', '295.99', 9, 'El refrigerador líquido para CPU CORSAIR iCUE H150i ELITE LCD XT ofrece una potente refrigeración personalizada con una pantalla LCD que muestra GIF, imágenes e información del sistema. Características destacadas incluyen: pantalla LCD IPS de 2.1", cabezal de bomba con anillo LED RGB, ventiladores PWM CORSAIR AF RGB ELITE, pasta térmica XTM70 Extreme Performance, y modo Zero RPM. Especificaciones: garantía de 5 años, compatibilidad con CORSAIR iCUE, tubos de 450 mm, pantalla de 480x480, y soporte para Intel y AMD.', 'Refrigeraciones/CorsairiCUEELITE/Im1.jpg', 'Refrigeraciones/CorsairiCUEELITE/Im2.jpg', 0),
('Corsair iCUE LINK H150i LCD Kit de Refrigeración Líquida 360mm Negro', 'Refrigeracion', '416.42', 10, 'El Corsair iCUE LINK H150i LCD es un poderoso refrigerador de CPU todo en uno con una pantalla LCD IPS ultrabrillante de 2,1”. Utiliza la tecnología iCUE LINK para una configuración más rápida y sencilla. La pantalla personalizable muestra información del sistema, GIF animados y más. Con una placa refrigerante de cobre y ventiladores QX120 RGB, ofrece un rendimiento excepcional. Control PWM para ajustar la velocidad de los ventiladores y compatibilidad con Zero RPM para reducir el ruido', 'Refrigeraciones/CorsairiCUELINK/Im1.jpg', 'Refrigeraciones/CorsairiCUELINK/Im2.jpg', 0),
('Corsair MP600 Pro XT SSD 8TB M.2 NVMe PCIe Gen 4x4', 'Disco duro', '1300.02', 9, 'La unidad SSD CORSAIR MP600 PRO XT Gen4 PCIe x4 NVMe 1.4 M.2 ofrece un rendimiento excepcional en el almacenamiento, aprovechando la tecnología Gen4 PCIe para alcanzar velocidades secuenciales de lectura y escritura increíblemente rápidas. Con un controlador de rendimiento extremo PCIe Gen4 x4, esta unidad garantiza tiempos de respuesta rápidos y un rendimiento superior. Su interfaz GEN4 PCIE X4 NVME 1.4 M.2 de alta velocidad proporciona un ancho de banda máximo para un rendimiento de almacenamiento excepcional. Además, cuenta con un difusor térmico de aluminio integrado para disipar el calor y mantener un alto rendimiento sostenido. ', 'DiscosDuros/CorsairMP600/Im1.jpg', 'DiscosDuros/CorsairMP600/Im2.jpg', 0),
('Corsair Vengeance DDR5 6400MHz 64GB 2x32GB CL32', 'Memoria RAM', '235.99', 8, 'La memoria CORSAIR VENGEANCE DDR5, diseñada para placas base Intel®, ofrece altas frecuencias y capacidades en un módulo compacto de alta calidad. Con chips de alta frecuencia seleccionados, overclocking fácil con regulación de voltaje incorporada y control a través del software CORSAIR iCUE. Un disipador de calor de aluminio sólido mantiene la memoria fresca, con garantía limitada de por vida. Características incluyen alto rendimiento, regulación de voltaje integrado, perfiles XMP 3.0 personalizados, y software iCUE para monitoreo y control. La memoria DDR5 ofrece mayor velocidad para un rendimiento rápido en procesamiento, renderizado y almacenamiento en búfer. Compacta y con chips de memoria seleccionados a mano, garantiza estabilidad y calidad. Con formato DIMM, velocidades de DDR5-6400 MHz y capacidad de 64GB (2 x 32GB), es compatible con placas base Intel 700 Series.', 'MemoriaRAM/CorsairVengeance6400/Im1.jpg', 'MemoriaRAM/CorsairVengeance6400/Im2.jpg', 0),
('Corsair Vengeance RGB DDR5 6000MHz PC5-48000 32GB 2x16GB CL36 Negra', 'Memoria RAM', '119.99', 10, 'La memoria CORSAIR VENGEANCE RGB DDR5 ofrece un rendimiento de vanguardia con frecuencias más altas y capacidades optimizadas para placas base Intel®, junto con una iluminación RGB dinámica de diez zonas. Los chips de alta frecuencia permiten un procesamiento más rápido y overclocking fácil. Con el software CORSAIR iCUE, se puede personalizar la iluminación RGB, controlar la frecuencia en tiempo real y los perfiles Intel XMP 3.0. La PCB personalizada garantiza estabilidad en placas base Intel DDR5.  Características adicionales incluyen perfiles XMP personalizados, control de iluminación dinámica y un disipador de calor de aluminio. Especificaciones: 32 GB (2 x 16 GB) de DDR5 a 6000 MHz, con latencia probada de 36-44-44-96, voltaje de 1,4 V, compatible con Intel Serie 600 y Serie 700.', 'MemoriaRAM/CorsairVengeance6000/Im1.jpg', 'MemoriaRAM/CorsairVengeance6000/Im2.jpg', 0),
('Corsair Vengeance RGB Pro SL DDR4 3200 MHz 256GB 8x32GB CL16', 'Memoria RAM', '2104.87', 10, 'La memoria CORSAIR VENGEANCE RGB PRO SL DDR4 ilumina el PC gracias a la iluminación dinámica RGB direccionable de forma individual, al tiempo que ofrece un rendimiento máximo en módulos de memoria compactos de 44 mm de altura.', 'MemoriaRAM/CorsairVengeance3200/Im1.jpg', 'MemoriaRAM/CorsairVengeance3200/Im2.jpg', 0),
('Crucial Ballistix Max DDR4 5100MHz PC4-40800 16GB 2x8GB CL19', 'Memoria RAM', '1245.98', 10, 'Características: Diseñada para overclocking extremo en juegos. Difusores térmicos de aluminio para disipación de calor. Sensores de temperatura para control térmico. Gran compatibilidad con AMD e Intel. Componentes de precisión para optimización del rendimiento. Especificaciones => Tipo de memoria: Unbuffered. Latencia CAS: 19. Memoria interna: 16 GB (2 x 8 GB). Tipo de memoria interna: DDR4. Velocidad de reloj: 5100 MHz. Componente para: PC/servidor. Forma de factor de memoria: 288-pin DIMM. ECC: No. Canales de memoria: Dual-channel. Voltaje de memoria: 1.5 V. Configuración de módulos: 2048M x 64. Tipo de enfriamiento: Disipador térmico.', 'MemoriaRAM/CrucialBallistix/Im1.jpg', 'MemoriaRAM/CrucialBallistix/Im2.jpg', 0),
('Crucial CT8G4DFRA32A DDR4 3200Mhz PC4-25600 8GB CL22', 'Memoria RAM', '19.99', 10, 'Sobre el producto: Aumente el rendimiento de su ordenador con la memoria de sobremesa Crucial®, una solución rentable para sistemas lentos. Cargue programas más rápido, multitarea sin interrupciones y maximice el valor de su sistema con facilidad de instalación y la calidad de Micron®.  Características: La memoria Crucial® mejora la velocidad y capacidad multitarea de su ordenador. La instalación es fácil, sin necesidad de conocimientos técnicos, y ofrece una excelente relación calidad-precio. Respaldada por Micron®, garantía de por vida limitada. Especificaciones: 8GB DDR4 a 3200 MHz, sin ECC, voltaje de memoria de 1.2V, diseñada para PC/servidor.', 'MemoriaRAM/Crucial/Im1.jpg', 'MemoriaRAM/Crucial/Im2.jpg', 0),
('Crucial T700 4TB PCIe Gen5 NVMe M.2 SSD con Disipador Térmico', 'Disco duro', '657.39', 10, '"La SSD Crucial T700 PCIe® 5.0 NVMe® ofrece velocidades de hasta 12,400 MB/s de lectura secuencial y hasta 11,800 MB/s de escritura secuencial (hasta 1500 K IOPS de lectura/escritura aleatoria) para acelerar los videojuegos, la edición de vídeo, el renderizado 3D y las aplicaciones de alto rendimiento. Lista para rendir con el difusor térmico de la placa base, la T700 se instala fácilmente en la ranura M.2. con una capacidad de hasta 4 TB.', 'DiscosDuros/CrucialT700/Im1.jpg', 'DiscosDuros/CrucialT700/Im2.jpg', 0),
('Dell 400-BCLW 2.5" SSD 480GB SAS', 'Disco duro', '1989.72', 9, 'Aumente la capacidad de almacenamiento de su sistema Dell™ con este disco de estado sólido (SSD) de 480 GB. Este SSD ofrece una velocidad de transferencia de datos de hasta 12 Gb/s, mejorando el acceso a los datos, los tiempos de inicio y las transferencias de archivos. Además, es más duradero y resistente a impactos que los discos duros mecánicos, siendo más ligero, silencioso y eficiente en términos de consumo de energía. Es compatible con una variedad de productos Dell, incluidos servidores y estaciones de trabajo', 'DiscosDuros/Dell400/Im1.jpg', 'DiscosDuros/Dell400/Im2.jpg', 0),
('Dell Precision 5680 Intel Core i9-13900H/32GB/1TB SSD/RTX 3500/16"', 'Portatil', '5909.38', 10, 'Sobre el producto: El Dell Precision 5680 es una estación de trabajo premium de 40,64 cm (16") para los usuarios que quieren un alto rendimiento y una gran pantalla en un chasis fino y ligero. Cuenta con una cámara de IR Full HD, panel táctil y 4 altavoces de calificación A. El portátil Precision 5680 ofrece un aspecto y sensación premium que ofrece un rendimiento excepcional. Gracias a una pantalla táctil OLED UHD+ opcional y 4 altavoces "nivel A", emparejados con tarjetas gráficas hasta NVIDIA RTX 5000 Ada Gen, es una estación de trabajo excepcional para aplicaciones creativas y de diseño.  Características:                                                ·Inteligencia construida a su alrededor: personalice e impulse automáticamente el rendimiento de su sistema y todo su ecosistema gracias a Dell Optimizer, un software de optimización basado en la IA que aprende sobre su manera de trabajar y responde en consecuencia.                                                     ·Rendimiento personalizado: la inteligencia y el aprendizaje automático aumentan la productividad mediante la personalización automática de las características de rendimiento en todo el ecosistema, lo que convierte estos equipos en los más inteligentes del mundo. ', 'Portatiles/DellPrecision/Im1.jpg', 'Portatiles/DellPrecision/Im2.jpg', 0),
('EVGA SuperNOVA 1000G XC 1000W 80 Plus Gold Full Modular', 'Fuente alimentación', '245.00', 10, 'La fuente de alimentación EVGA SuperNOVA 1000G XC, compatible con ATX 3.0 y PCIe 5.0, ofrece alta estabilidad y eficiencia con certificación 80 PLUS Gold. Con controladores y condensadores japoneses, proporciona baja ondulación y ruido. Incluye un cable nativo de 12 VHPWR y protecciones completas. Totalmente modular y con el sistema de control térmico EVGA ECO, garantiza un rendimiento silencioso y eficiente para sistemas de juego modernos.', 'FuentesAlimentacion/EVGASuperNOVA1000G/Im1.jpg', 'FuentesAlimentacion/EVGASuperNOVA1000G/Im2.jpg', 0),
('EVGA SuperNOVA 1300 G+ 80 Plus Gold 1300W Full Modular', 'Fuente alimentación', '278.99', 9, 'La SuperNOVA 1300 G+, una fuente de alimentación de EVGA, ofrece una eficiencia del 90% o más, con certificación 80 PLUS Gold. Totalmente modular, con condensadores japoneses y protecciones de alta resistencia. Cuenta con un ventilador ultra silencioso, sistema de control térmico EVGA ECO y garantía global de 10 años.', 'FuentesAlimentacion/EVGASuperNOVA1300G/Im1.jpg', 'FuentesAlimentacion/EVGASuperNOVA1300G/Im2.jpg', 0),
('Forgeon Bolt PSU 1000W 80+ Gold Full Modular Blanca', 'Fuente alimentación', '210.00', 10, 'La certificación 80 PLUS Gold garantiza una alta eficiencia energética para un consumo óptimo. La fuente Forgeon Bolt ofrece cables modulares, 100% capacitadores japoneses, y protecciones contra sobretensiones, cortocircuitos y sobrecalentamiento. Con una potencia de 850W, dimensiones de 150mm x 86mm x 160mm, y un peso de 2,7Kg, es compatible con ATX. Incluye diversos conectores y accesorios, con un ventilador de 14 cm para refrigeración activa.', 'FuentesAlimentacion/ForgeonBolt/Im1.jpg', 'FuentesAlimentacion/ForgeonBolt/Im2.jpg', 0),
('Forgeon Solarian Cooler 4Pipes 120mm ARGB Ventilador CPU Blanco', 'Refrigeracion', '59.99', 10, 'Hoy desde FORGEON presentamos el nuevo disipador Solarian Cooler 4 Pipes, disponible en blanco y negro, ofrece una potencia de disipación de 130W TDP con 4 tubos y ventilador incluido. Con medidas de 158mm x 122mm x 76mm, su instalación es fácil y garantiza protección al procesador a una temperatura óptima. Características: Compatible con Intel y AMD, sistema A-RGB incluido para personalización, y capacidad de overclocking con 1800 RPM y 27,5 dB de ruido. Especificaciones: Modelo FORGEON Solarian, compatible con varios sockets, 4 tubos de disipador de calor, y vida estimada de uso de 50.000h.', 'Refrigeraciones/ForgeonSolarian/Im1.jpg', 'Refrigeraciones/ForgeonSolarian/Im2.jpg', 0),
('FSP Twins PRO Fuente de Alimentación Redundante 500W 80 Plus Gold', 'Fuente alimentación', '583.00', 10, 'Características de FSP Twins PRO: Compatible con ATX PS2 redundante, eficiencia superior al 90% a carga típica, ventilador silencioso y duradero con rodamiento de bolas de 40 mm, cables de cinta para entusiastas, diseño potente de riel único de +12 V, condensadores electrolíticos japoneses, listo para CPU Intel más reciente y protecciones completas OCP, OVP, SCP, OPP, OTP, FFP, UVP. Especificaciones: Potencia de salida nominal de 500W, certificación 80 PLUS Gold, voltaje de entrada de 100-240 Vac, corriente de entrada de 8-4 A, frecuencia de entrada de 60-50 Hz, PFC activo, eficiencia del 90%, ventilador con doble rodamiento de bolas de 40 mm y dimensiones de 150 x 86 x 190 mm.', 'FuentesAlimentacion/FSPTwin/Im1.jpg', 'FuentesAlimentacion/FSPTwin/Im2.jpg', 0),
('Gigabyte B550M Aorus Elite', 'Placa base', '89.99', 9, 'La placa base Gigabyte B550M AORUS ELITE es compatible con procesadores AMD Ryzen de tercera generación. Cuenta con características como soporte para memoria DDR4, ranuras PCIe 4.0 y 3.0, conectores M.2 para SSDs, LAN GbE Gaming, salida HDMI y DVI, y RGB FUSION 2.0. Incluye funciones como Q-Flash Plus para actualizar BIOS sin CPU, memoria o tarjeta gráfica. Admite hasta 128 GB de memoria DDR4 y ofrece varias opciones de conectividad y almacenamiento. El diseño Micro ATX lo hace adecuado para configuraciones compactas.', 'PlacasBases/GigabyteB550M/Im1.jpg', 'PlacasBases/GigabyteB550M/Im2.jpg', 0),
('Gigabyte GeForce RTX 4060 EAGLE OC 8GB GDDR6 DLSS3', 'Tarjeta Grafica', '349.99', 10, 'El producto cuenta con tecnología NVIDIA DLSS 3, arquitectura ultraeficiente Ada Lovelace y trazado de rayos completo. Los núcleos tensoriales de 4.ª generación ofrecen hasta 4 veces más rendimiento con DLSS 3. Los núcleos RT de tercera generación brindan un rendimiento de trazado de rayos hasta 2 veces mayor. Desarrollado por GeForce RTX™ 4060, tiene una memoria integrada de 8 GB GDDR6 con una interfaz de 128 bits. Presenta un sistema de refrigeración WINDFORCE, BIOS doble y placa trasera de protección. La tarjeta tiene un reloj de núcleo de 2505 MHz, 3072 núcleos CUDA y una velocidad de memoria de 17 Gb/s. Es compatible con DirectX 12 y OpenGL 4.6, con resolución máxima digital de 7680x4320 y múltiples vistas. El tamaño de la tarjeta es L=272mm, W=115mm, H=40mm y requiere una fuente de alimentación de 450W con un conector de 8 pines. Viene con DisplayPort 1.4a2, HDMI2.1a2 y una guía rápida de accesorios', 'TarjetasGraficas/Gigabyte4060/Im1.jpg', 'TarjetasGraficas/Gigabyte4060/Im2.jpg', 0),
('Gigabyte GeForce RTX 4070 SUPER WINDFORCE OC 12GB GDDR6X DLSS3', 'Tarjeta Grafica', '689.90', 10, 'El sistema de enfriamiento WINDFORCE ofrece alta eficiencia con tres ventiladores únicos, tubos de calor de cobre y ventiladores activos. La serie GeForce RTX 40 presenta tecnología Ada Lovelace para gráficos ultrarrápidos y realistas, con trazado de rayos hiperrealista y DLSS 3 para mejor rendimiento. NVIDIA Reflex asegura baja latencia. Características incluyen DLSS 3, arquitectura Ada Lovelace y trazado de rayos. Especificaciones de la Gigabyte GeForce RTX 4070 SUPER WINDFORCE OC: procesador GeForce RTX 4070, memoria de 12 GB GDDR6X, interfaz PCI Express 4.0, entre otros', 'TarjetasGraficas/Gigabyte4070_12GB/Im1.jpg', 'TarjetasGraficas/Gigabyte4070_12GB/Im2.jpg', 0),
('Gigabyte GeForce RTX 4070 Ti SUPER WINDFORCE OC 16GB GDDR6X DLSS3', 'Tarjeta Grafica', '929.00', 10, 'El sistema de enfriamiento WINDFORCE garantiza una disipación eficiente del calor, mientras que las GPU NVIDIA GeForce RTX serie 40 ofrecen un rendimiento excepcional tanto para juegos como para tareas creativas. Con tecnologías como el trazado de rayos, DLSS 3 y NVIDIA Reflex, estas tarjetas proporcionan una experiencia de juego avanzada. La Gigabyte GeForce RTX 4070 Ti SUPER WINDFORCE OC ofrece especificaciones detalladas para satisfacer las necesidades de los usuarios exigentes.', 'TarjetasGraficas/Gigabyte4070_16GB/Im1.jpg', 'TarjetasGraficas/Gigabyte4070_16GB/Im2.jpg', 0),
('Gigabyte H510M H V2', 'Placa base', '68.99', 10, 'La placa base Gigabyte Ultra Durable es compatible con procesadores Intel® Core™ de 11.ª y 10.ª generación, DDR4 de dos canales, GbE LAN, resistencia anti-azufre y Smart Fan 5. Incluye características como audio HD de 8 canales, conector NVMe PCIe Gen3 x4 2280 M.2 y LAN GbE con gestión de ancho de banda. Especificaciones: procesador Intel, socket LGA 1200, memoria DDR4-SDRAM, soporte para unidades M.2, SATA III, interfaces USB 2.0 y USB 3.2 Gen 1, chipset Intel H510 Express, factor de forma micro ATX, y compatibilidad con Windows 10 x64.', 'PlacasBases/GigabyteH510M/Im1.jpg', 'PlacasBases/GigabyteH510M/Im2.jpg', 0),
('HP OMEN 40L GT21-1033ns AMD Ryzen 7 7700X/16GB/1TB SSD/RTX 4070', 'Torre', '1599.00', 10, 'El sobremesa OMEN by HP 40L lleva tus juegos a un nuevo nivel con su procesador AMD Ryzen 7 de última generación y gráficos avanzados. Con un sistema de refrigeración superior y un diseño sin necesidad de herramientas, este PC está diseñado para ofrecer el máximo rendimiento para satisfacer todas tus necesidades como gamer. Características incluyen ventiladores estratégicamente colocados, diseño sin herramientas para ampliación y actualización, y tecnología avanzada como GPU NVIDIA GeForce RTX de la serie 40 y unidad de estado sólido de 1TB. El OMEN 40L también cuenta con OMEN Gaming Hub, tecnología DTS:X Ultra, USB Type-C reversible, memoria de doble canal, y más. Especificaciones detalladas incluyen un procesador AMD Ryzen 7 7700X, 16GB de memoria DDR5, gráficos NVIDIA GeForce RTX 4060 Ti con 12GB de memoria, y conectividad Wi-Fi 6E. El diseño sostenible del producto y características como OMEN Light Studio y OMEN CRYO CHAMBER lo convierten en una opción ideal para los jugadores exigentes.', 'Torres/HPOMEN40L/Im1.jpg', 'Torres/HPOMEN40L/Im2.jpg', 0),
('HP OMEN 45L GT22-1017ns Intel Core i9-13900K/64GB/2TB SSD/RTX 4090', 'Torre', '4099.00', 8, 'El sobremesa gaming OMEN by HP 45L ofrece un rendimiento extremo con el procesador Intel Core i9 de 13ª generación y la gráfica NVIDIA GeForce RTX 4090. Incorpora refrigeración líquida para mantener una temperatura óptima, y memoria RAM DDR5 de 64 GB para un rendimiento multitarea superior. Con Wi-Fi 6E y Bluetooth 5.2, ofrece una conectividad rápida y estable. \nEl OMEN Gaming Hub y OMEN Light Studio permiten personalizar la experiencia de juego. El diseño de torre incluye iluminación RGB y sistema de refrigeración por agua. Viene con FreeDOS instalado. Certificado ENERGY STAR y EPEAT Gold, y con materiales sostenibles.\nIncluye una fuente de alimentación de 1200W 80 PLUS Gold. Dimensiones: 204mm x 470mm x 555mm, peso: 22.6kg.', 'Torres/HPOMEN45L/Im1.jpg', 'Torres/HPOMEN45L/Im2.jpg', 0),
('HP Pavilion Desktop TP01-4006ns Intel Core i5-13400/16GB/512GB SSD', 'Torre', '649.00', 10, 'El HP Pavilion Desktop es un ordenador fiable diseñado para el hogar moderno, con alto\nrendimiento y diseño probado. Equipado con procesador Intel® Core™ i5 de 13ma Generación,\n16 GB de RAM DDR4, y almacenamiento SSD de 512 GB, ofrece eficacia en tareas diarias.\nIncluye puertos frontales, Windows 11, y tecnología Bluetooth® integrada. Características\nsostenibles y de seguridad. Dimensiones: 155,4 x 304 x 337,4 mm. Peso: 5,96 kg. Fuente de\nalimentación de 400 W. Sistema operativo: Windows 11 Home.', 'Torres/HPPavilion/Im1.jpg', 'Torres/HPPavilion/Im2.jpg', 0),
('HP Slim Desktop S01-pF2027ns Intel Core i5-12400/8GB/256GB SSD', 'Torre', '429.01', 10, 'HP presenta un ordenador de sobremesa que combina tecnología probada con un diseño\ndelgado para ahorrar espacio. Equipado con un procesador rápido y gran capacidad de\nalmacenamiento, este ordenador es ideal para tareas cotidianas. Cuenta con múltiples\npuertos, un diseño resistente y está respaldado por la confianza de HP. Especificaciones\nincluyen un procesador Intel® Core™ i5-12400, 8 GB de RAM DDR4, y un SSD de 256 GB.\nConexiones Wi-Fi, Bluetooth, Ethernet y varios puertos USB. Diseño de torre en color negro.\nIncluye sistema operativo FreeDOS.', 'Torres/HPSlim/Im1.jpg', 'Torres/HPSlim/Im2.jpg', 0),
('IceGiant Prosiphon Elite Ventilador CPU 2x120mm', 'Refrigeracion', '200.82', 9, 'El IceGiant ProSiphon Elite ofrece una gran superficie de contacto adecuada no solo para CPU estándar de AMD e Intel, sino también para procesadores de alto rendimiento como AMD Ryzen Threadripper. Con cuatro ventiladores de 120 mm en configuración push-pull, la exclusiva tecnología ProSiphon garantiza un rendimiento de refrigeración óptimo. El líquido refrigerante circula sin bomba en circuito cerrado, transportando el calor desde la CPU al enfriador sin ruido ni mantenimiento. Especificaciones: Dimensiones (con 2 ventiladores): 251 x 164 x 104 mm, Dimensiones (con 4 ventiladores): 251 x 164 x 129,4 mm, Material: Aluminio, Peso: 1440 g (sin ventiladores) / 2000 g (con ventiladores), Ventiladores: 4x 120 mm PWM, Sonoridad: 32,2 dB (A) a 2300 rpm, Conexión: 4Pin-PWM, Compatibilidad: Intel: 1200 / 115x / 1366/2011 (-3) / 2066, AMD: AM4 / TR4 / sTRX4, Altura de RAM: máx. 48 mm', 'Refrigeraciones/IceGiant/Im1.jpg', 'Refrigeraciones/IceGiant/Im2.jpg', 0),
('Intel Celeron G5905 3.50GHz', 'CPU', '44.99', 8, 'Los procesadores Intel® Core™ de 10ª generación ofrecen mejoras notables en rendimiento, incluyendo Intel® Wi-Fi 6 (Gig+), Thunderbolt™ 3, HDR 4K y más. Características: Compatible con la memoria Intel® Optane™ para acelerar el desempeño, tecnología Intel® Turbo Boost para aumentar la frecuencia del procesador dinámicamente, tecnología de virtualización Intel® (VT-x) para funcionar como varias plataformas virtuales, tecnología de virtualización Intel® para E/S dirigida (VT-d) para mejorar la seguridad y la confiabilidad, intel® VT-x con tablas de páginas extendidas (EPT) para acelerar aplicaciones virtualizadas, arquitectura Intel® 64 para procesamiento informático de 64 bits, extensiones de conjunto de instrucciones como SSE y AVX, tecnología Intel SpeedStep® mejorada para alto rendimiento y conservación de energía, tecnologías de monitoreo térmico para proteger el procesador y tecnología Intel® Identity Protection para autenticación segura. Especificaciones: Procesador Intel® Celeron® G5905, frecuencia base de 3,5 GHz, 2 núcleos y 4 MB de caché y soporte para hasta 128 GB de memoria DDR4-SDRAM a 2666 MHz.', 'CPU/IntelCeleron/Im1.jpg', 'CPU/IntelCeleron/Im2.jpg', 0),
('Intel Core i5-12400F 2.5 GHz', 'CPU', '135.90', 10, 'Procesadores Intel® Core™ de 12ª generación: Introduciendo una arquitectura híbrida revolucionaria con núcleos de rendimiento y eficiencia, los procesadores Intel® Core™ de 12ª generación ofrecen un rendimiento excepcional en una variedad de tareas. Desde juegos hasta trabajo remoto, estos procesadores proporcionan un rendimiento escalable y versátil. Características: · Arquitectura híbrida: Combina núcleos de rendimiento y eficiencia para un rendimiento óptimo en diversas aplicaciones. · Rendimiento superior: Ya sea para juegos exigentes o tareas diarias, estos procesadores ofrecen el rendimiento que necesitas. Especificaciones clave: LGA 1700 socket, hasta 6 núcleos de rendimiento, DDR5 4800 / DDR4 3200 velocidad de memoria, PCIe 5.0 y 4.0, capacidad de hasta 128GB de memoria, y más.', 'CPU/IntelCorei5_12400F/Im1.jpg', 'CPU/IntelCorei5_12400F/Im2.jpg', 0),
('Intel Core i5-14600KF 3.5/5.4GHz Box', 'CPU', '299.90', 10, 'El procesador Intel Core i5 LGA1700 es una potente unidad de procesamiento con 14 núcleos y 20 hilos, destacándose por su rendimiento excepcional y versatilidad. Con una frecuencia de 3500 MHz y un caché L3 de 24576 KB, ofrece un rendimiento fluido en multitarea y aplicaciones exigentes. Pertenece a la serie 14ª generación, con arquitectura Raptor Lake Refresh para eficiencia energética. Su multiplicador desbloqueado brinda flexibilidad para overclocking. Especificaciones: 6 P-Cores, 8 E-Cores, frecuencia máxima de 5.40 GHz, y TDP de 125 W.', 'CPU/IntelCorei5_14600KF/Im1.jpg', 'CPU/IntelCorei5_14600KF/Im2.jpg', 0),
('Intel Core i7-13700KF 3.4 GHz Box', 'CPU', '436.99', 10, 'Los procesadores Intel® Core™ de 13ª generación para equipos de sobremesa ofrecen un rendimiento superior con hasta 24 núcleos (8 Performance-cores y 16 Efficient-cores), alcanzando 5,8 GHz con Intel® Thermal Velocity Boost. La tecnología Intel® Turbo Boost Max 3.0 mejora el rendimiento en hilos ligeros, mientras que los E-cores adicionales permiten una mayor caché inteligente. Equipados con hasta 16 carriles PCIe 5.0, compatibilidad con DDR5, y capacidades de overclocking avanzadas. Proporcionan una experiencia inmersiva con gráficos Intel® UHD mejorados y conectividad líder en su clase. Especificaciones del procesador: i7 - 13700KF, 16 núcleos, 24 hilos, frecuencia turbo de 5,4 GHz, TDP de 125 W, y soporte para DDR4-SDRAM y DDR5-SDRAM. Disponible para escritorio, con tecnologías de seguridad y virtualización de Intel integradas.', 'CPU/IntelCorei7_13700KF/Im1.jpg', 'CPU/IntelCorei7_13700KF/Im2.jpg', 0),
('Intel Core i7-14700KF 3.4/5.6GHz Box', 'CPU', '399.91', 10, 'El procesador Intel Core i7-14700KF es una poderosa unidad de procesamiento con 8 núcleos P-Core y 12 núcleos E-Core. Ofrece una frecuencia base de 3,40 GHz para los P-Core y una impresionante frecuencia máxima de 5,60 GHz. Con 33 MB de caché, es ideal para tareas intensivas y aplicaciones demandantes. Compatible con placas base LGA1700 y la microarquitectura Raptor Lake Refresh. Su multiplicador desbloqueado permite overclocking. Especificaciones: 20 núcleos, TDP de 125 W, y soporte para DDR4-SDRAM y DDR5-SDRAM.', 'CPU/IntelCorei7_14700KF/Im1.jpg', 'CPU/IntelCorei7_14700KF/Im2.jpg', 0),
('Intel Core i9-10980XE 3 GHz Extreme Edition', 'CPU', '1331.60', 10, 'El procesador Intel Core serie X i9-10980XE es compatible con la memoria Intel Optane, ofreciendo un rendimiento y capacidad de respuesta mejorados. La Tecnología Intel Turbo Boost aumenta dinámicamente la frecuencia del procesador según las necesidades, mientras que la Tecnología Hyper-Threading permite más trabajo en paralelo. La Tecnología de virtualización Intel (VT-x) y la Tecnología de virtualización de Intel para E/S dirigida (VT-d) ofrecen capacidades de virtualización avanzadas. Además, la arquitectura Intel 64 permite el procesamiento de 64 bits.  Con instrucciones adicionales como AVX-512, el procesador mejora el rendimiento en operaciones de datos. La Tecnología Intel SpeedStep mejorada garantiza un alto rendimiento y eficiencia energética. El procesador también es compatible con Intel Deep Learning Boost para acelerar el aprendizaje profundo. Especificaciones: 18 núcleos, 36 hilos, frecuencia base de 3 GHz, turbo de 4,6 GHz, 24,75 MB de caché, TDP de 165 W, soporte para DDR4-SDRAM, y máximo de 256 GB de memoria. Compatible con ECC y memoria DDR4- SDRAM hasta 2933 MHz. Ofrece seguridad con Execute Disable Bit y admite hasta 48 buses PCI Express.', 'CPU/IntelCorei9/Im1.jpg', 'CPU/IntelCorei9/Im2.jpg', 0);
INSERT INTO `productos` (`IdNombre`, `tipoProducto`, `precioProducto`, `stockProducto`, `descripcionProducto`, `imagen1Producto`, `imagen2Producto`, `oculto`) VALUES
('Kingston A400 SSD 240GB', 'Disco duro', '25.99', 10, 'La unidad de estado sólido A400 de Kingston ofrece mejoras significativas en la velocidad de respuesta sin necesidad de actualizaciones adicionales de hardware. Con velocidades de lectura y escritura de hasta 500 MB/s y 450 MB/s respectivamente, es 10 veces más rápida que los discos duros tradicionales. Además, es más fiable y duradera. Disponible en capacidades de 120 GB a 480 GB. Características: Arranques, cargas y transferencias de archivos más rápidos. Más fiable que los discos duros. Varias capacidades disponibles. Especificaciones: Capacidad de 240 GB. Velocidad de lectura de 500 MB/s y escritura de 350 MB/s. Interfaz SATA III. Factor de forma de 2.5 pulgadas. Compatible con Windows, macOS y Linux. Color negro. Certificaciones CE y FCC.', 'DiscosDuros/KingstonA400/Im1.jpg', 'DiscosDuros/KingstonA400/Im2.jpg', 0),
('Kingston DC600M 2.5” SSD 3.84 TB Uso Mixto Enterprise SATA 3.0', 'Disco duro', '512.94', 10, '"La unidad DC600M de Kingston ofrece protección contra cortes de alimentación mediante condensadores PLP, excelente Calidad de Servicio (QoS) para cumplir con los SLA, y cifrado AES 256-bit. Con capacidades de hasta 7680 GB, esta unidad SATA Rev. 3.0 (6 GB/s) ofrece lecturas/escrituras secuenciales de hasta 560 MB/s y 530 MB/s respectivamente, y lecturas/escrituras 4k aleatorias estables de hasta 94,000/59,000 IOPS. Ofrece herramientas Enterprise SMART para seguimiento de fiabilidad y tiene una durabilidad de hasta 7008 TBW con 1-1.66 DWPD. Consumo eléctrico en reposo de 1.30 W y temperatura de servicio de 0 °C a 70 °C. Dimensiones: 69.9 mm x 100 mm x 7 mm. Peso: 92.34 g. MTBF de 2 millones de horas', 'DiscosDuros/KingstonDC600M/Im1.jpg', 'DiscosDuros/KingstonDC600M/Im2.jpg', 0),
('Kingston FURY Beast DDR5 5600MHz 64GB 2x32GB CL36', 'Memoria RAM', '236.50', 9, 'La memoria Kingston FURY™ Beast DDR5 trae la tecnología más novedosa para plataformas de juego de nueva generación. DDR5 empuja los límites de velocidad, capacidad y fiabilidad con novedades como ECC interno (ODECC) para estabilidad a altas velocidades, dobles subcanales de 32 bits y PMIC para inyectar energía cuando se necesita. Los notables avances en velocidad, con la duplicación de bancos y longitud de ráfaga, llevan a nuevos niveles de juego y aplicaciones del sistema. La memoria Kingston FURY Beast DDR5 ofrece rendimiento sin límites y diseño. Con opciones como Intel® XMP 3.0 o AMD EXPO™, puede cubrir sus soluciones de overclocking compatibles.', 'MemoriaRAM/KingstonFURYBeastDDR5/Im1.jpg', 'MemoriaRAM/KingstonFURYBeastDDR5/Im2.jpg', 0),
('Kingston FURY Beast RGB DDR4 3200MHz 16GB 2x8GB CL16', 'Memoria RAM', '50.00', 10, 'Sobre el producto: El módulo de memoria RAM DDR4 RGB FURY Beast de Kingston ofrece un aumento del rendimiento con velocidades de 2666MHz a 3733MHz y estilo agresivo con iluminación RGB. Disponible en capacidades de 8GB a 32GB como módulo individual y de 16GB a 128GB como kit. Compatible con Intel XMP y Ryzen. El disipador del módulo FURY Beast DDR4 RGB garantiza una temperatura óptima. Probado al 100% y garantizado de por vida, es fácil de instalar en sistemas Intel o AMD. Características: Iluminación RGB impresionante, tecnología patentada de sincronización por infrarrojos Kingston FURY, velocidades de hasta 3733MHz y capacidades de hasta 128GB.  Especificaciones Kingston FURY Beast RGB: Capacidad de 16GB, frecuencia de memoria DDR4 de 3200 MHz, 2 módulos de memoria de 8GB cada uno, LED y LED RGB, radiador negro, sin ventilador suministrado, con tiempos de latencia CAS Latency de 16, RAS to CAS Delay de 17 y RAS Precharge Time de 17. Compatible con una tensión mínima de 1.35 Voltios.', 'MemoriaRAM/KingstonFURYBeastDDR4/Im1.jpg', 'MemoriaRAM/KingstonFURYBeastDDR4/Im2.jpg', 0),
('Kingston NV2 1TB SSD PCIe 4.0 NVMe Gen 4x4', 'Disco duro', '63.98', 10, 'El disco SSD NVMe PCIe 4.0 NV2 ofrece velocidades de lectura/escritura de hasta 3.500/2.800 MB/s, con bajo consumo eléctrico y calor reducido. Su diseño compacto M.2 2280 de una cara amplía el almacenamiento hasta 2 TB, ideal para portátiles delgados y sistemas de pequeño factor de forma. Especificaciones: Factor de forma M.2 2280, interfaz PCIe 4.0 x4 NVMe, capacidad de 1 TB, lectura/escritura secuencial de 3.500/2.100 MB/s, resistencia de hasta 320 TB, temperatura de almacenamiento -40 °C ~ 85 °C, garantía limitada de 3 años.', 'DiscosDuros/KingstonNV2/Im1.jpg', 'DiscosDuros/KingstonNV2/Im2.jpg', 0),
('Kioxia Exceria Pro Unidad SSD 1TB NVMe M.2 2280 PCIe Gen4 x4', 'Disco duro', '86.99', 10, 'La serie EXCERIA PRO de KIOXIA ofrece unidades SSD de alto rendimiento con tecnología PCIe 4.0 y NVMe 1.4, hasta 2 TB de capacidad. Con diseño M.2 2280, ofrece una conexión directa a la placa madre. Fabricada con BiCS FLASH, ofrece un rendimiento potente para jugadores y creadores de contenido. Características: BiCS FLASH, NVMe 1.4, PCIe Gen4 x4, SSD Utility Management Software. Especificaciones: Capacidad de 1 TB, diseño M.2 2280, interfaz PCIe 4.0, velocidad máxima de lectura secuencial de 7300 MB/s y escritura de 6400 MB/s. Resistencia de 400 TBW, MTTF de 1.5 millones de horas. Compatible con PCI Express 4.0 y NVM Express 1.4. Garantía de 5 años del fabricante', 'DiscosDuros/KioxiaExceria/Im1.jpg', 'DiscosDuros/KioxiaExceria/Im2.jpg', 0),
('Lenovo IdeaPad Slim 3 15IAH8 Intel Core i5-12450H/16GB/1TB SSD/15.6"', 'Portatil', '689.00', 9, 'La computadora portátil Lenovo IdeaPad Slim 3 es perfecta para destacar en cualquier lugar. Diseñada con construcción robusta y durabilidad de grado militar, esta portátil es liviana y delgada, ideal para resistir caídas y condiciones extremas de viaje. Con los últimos procesadores Intel y 16GB de RAM LPDDR5-4800, ofrece un rendimiento sólido para múltiples aplicaciones. La pantalla de 15.6" FHD con Dolby Audio™ garantiza una experiencia multimedia inmersiva. Con Wi-Fi® 6, puertos versátiles y la inteligencia artificial de Lenovo AI Engine, esta portátil se adapta a tus necesidades. Especificaciones incluyen un procesador Intel® Core™ i5- 12450H, 1TB de almacenamiento SSD, y Windows 11 Home. Dimensiones: 359,3 x 235 x 17,9 mm. Peso: 1,62 kg. Color: Gris Ártico.', 'Portatiles/LenovoIdeaPad/Im1.jpg', 'Portatiles/LenovoIdeaPad/Im2.jpg', 0),
('Lenovo Legion PRO 7 16IRX8H-876 Intel Core i9-13900HX/32GB/1TB SSD/RTX 4090/16'''' (PT)', 'Portatil', '5876.36', 10, 'El Lenovo Legion Pro 7i Gen 8 (16" Intel) es un portátil para juegos optimizado para IA líder en la industria. Presenta un rendimiento optimizado para IA a través de la tecnología Lenovo AI Engine+. La solución de refrigeración integrada Legion Coldfront 5.0 garantiza un rendimiento óptimo. Fabricado con materiales sostenibles como polímero orgánico y aluminio reciclado. La pantalla de 16" ofrece una experiencia visual excepcional con resolución WQXGA y frecuencia de actualización de hasta 240Hz. Especificaciones: Procesador Intel Core i9-13900HX, 32GB RAM DDR5, 1TB SSD PCIe 4.0, NVIDIA GeForce RTX 4090. Conectividad completa con Wi-Fi 6E y Bluetooth 5.1. Teclado con iluminación RGB y diseño portugués. Sistema operativo Windows 11 Home. Dimensiones: 363,4 x 262,15 x 21,95~25,9 mm. Peso: 2,8 kg. Color: Gris (Onyx Grey).', 'Portatiles/LenovoLegion/Im1.jpg', 'Portatiles/LenovoLegion/Im2.jpg', 0),
('Lenovo V15 G3 IAP Intel Core i3-1215U/8 GB/256GB SSD/15.6"', 'Portatil', '349.00', 10, 'El Lenovo V15 de 3.ª generación es ideal para trabajar o estudiar sobre la marcha, con un procesador Intel® Core™ de 12.ª generación y tarjeta gráfica Intel® UHD Graphics. Ofrece una excelente conectividad, pantalla de 15,6" con Dolby Audio™ y funciones Smart de videoconferencias. Con procesadores Intel® Core™ de alta velocidad, gran capacidad de memoria y almacenamiento, y funciones de seguridad mejoradas. Especificaciones: Procesador Intel® Core™ i3-1215U, 8GB de RAM DDR4, 256GB SSD PCIe, pantalla FHD de 15.6", WiFi 802.11ac, Bluetooth 5.1, Webcam HD 720p con obturador de privacidad, altavoces estéreo Dolby Audio, diversas conexiones y medidas de seguridad como Firmware TPM 2.0 y ranura de seguridad Kensington Nano. Sin Sistema Operativo. Dimensiones: 359 x 236 x 19.9 mm, Peso: 1.7 kg, Color: Negro (Business Black).', 'Portatiles/LenovoV15/Im1.jpg', 'Portatiles/LenovoV15/Im2.jpg', 0),
('MSI B760 GAMING PLUS WIFI', 'Placa base', '149.89', 7, 'La placa base MSI B760 GAMING PLUS WIFI está diseñada para jugadores que buscan conectividad, flexibilidad y una solución Wi-Fi conveniente. Admite procesadores Intel® Core™, Pentium® Gold y Celeron® de 12.ª y 13.ª generación, así como memoria DDR5 hasta 6800 + MHz (OC). Presenta un diseño de alimentación mejorado, solución térmica premium y experiencia de juego ultrarrápida con ranura PCIe 4.0, Lightning Gen 4 x4 M.2 y Turbo USB 3.2 Gen 2 10G. Incluye LAN 2.5G con Wi-Fi 6E, PCB de alta calidad y Audio Boost para una calidad de sonido de estudio.  Especificaciones: Soporte para procesadores Intel, chipset Intel B760, memoria DDR5, interfaces de almacenamiento M.2 y SATA, LAN 2.5 Gigabit Ethernet, Wi-Fi 6E, Bluetooth 5.3, audio Realtek ALC897 de 7.1 canales, factor de forma ATX, y ranuras de expansión PCIe y M.2.', 'PlacasBases/MSIB760/Im1.jpg', 'PlacasBases/MSIB760/Im2.jpg', 0),
('MSI GeForce RTX 4070 VENTUS 3X E OC 12GB GDDR6 DLSS3', 'Tarjeta Grafica', '709.00', 10, 'El producto es la NVIDIA® GeForce RTX™ 4070, con arquitectura Ada Lovelace para trazado de rayos rápido y DLSS 3 para rendimiento acelerado por IA. La serie GeForce RTX 40 ofrece gráficos ultrarrápidos y realistas, con baja latencia gracias a NVIDIA Reflex. Las especificaciones de la MSI GeForce RTX 4070 VENTUS 3X E OC incluyen una unidad de procesamiento de gráficos GeForce RTX 4070, interfaz PCI Express Gen 4, 12GB de memoria GDDR6X y más.', 'TarjetasGraficas/MSI4070/Im1.jpg', 'TarjetasGraficas/MSI4070/Im2.jpg', 0),
('MSI Katana 15 B12VFK-1412XES Intel Core i7-12650H/16GB/1TB SSD/RTX 4060/15.6"', 'Portatil', '949.00', 10, 'Sobre el producto: La espada Katana 15 B12V te invita a proteger tu honor y derrotar a tus enemigos con su poder ancestral. Equipada con GPU NVIDIA® GeForce RTX™ Serie 40, ofrece un rendimiento excepcional tanto para jugadores como creadores. Con un teclado RGB de 4 zonas, brinda una experiencia de juego inmersiva y elegante. Características: Procesador hasta Intel® Core™ i7-12650H, GPU GeForce RTX™ 40, pantalla Full HD de 15.6" con frecuencia de actualización de 144 Hz. Cooler Boost 5 y MSI App Player para una experiencia óptima. Especificaciones: Procesador Alder Lake i7-12650H, memoria RAM DDR5 8GB*2, almacenamiento 1TB NVMe PCIe SSD Gen4x4. Conexiones variadas, incluyendo USB Type-C y RJ45. Sin sistema operativo.', 'Portatiles/MSIKatana/Im1.jpg', 'Portatiles/MSIKatana/Im2.jpg', 0),
('MSI MAG A650GL 650W 80 Plus Gold Modular', 'Fuente alimentación', '102.72', 10, 'La serie MAG de MSI ofrece productos robustos y duraderos, con una fuente de alimentación eficiente que influye directamente en el rendimiento del sistema. Presenta características como tamaño compacto, organización de cables simplificada, cojinete dinámico fluido y mecanismos de protección integrados, junto con especificaciones de alto rendimiento y certificación 80 PLUS Gold.', 'FuentesAlimentacion/MSIMAG/Im1.jpg', 'FuentesAlimentacion/MSIMAG/Im2.jpg', 0),
('MSI MAG B550 TOMAHAWK', 'Placa base', '148.99', 11, 'La placa base MAG B550 TOMAHAWK ofrece soporte para procesadores AMD Ryzen™ de tercera generación y futuros procesadores Ryzen™ con actualización del BIOS. Admite memoria DDR4 hasta 5100+ (OC) MHz, con experiencia de juego ultrarrápida gracias a PCIe 4.0, Lightning Gen 4 x4 M.2 y AMD Turbo USB 3.2 Gen 2. Presenta una solución térmica de primera calidad, diseño de potencia mejorado, última solución de red con LAN 2.5G y Gigabit LAN, Mystic Light para personalización de colores, blindaje de E/S preinstalado y Audio Boost para una calidad de sonido de grado de estudio. Especificaciones: Soporte para procesadores AMD Ryzen™, chipset AMD B550, interfaces de almacenamiento M.2 y SATA, ranuras de expansión PCIe, RAID para dispositivos de almacenamiento SATA, puertos USB y LAN Realtek®.', 'PlacasBases/MSIMAG/Im1.jpg', 'PlacasBases/MSIMAG/Im2.jpg', 0),
('MSI MAG Infinite S3 13NUC5-1212XES Intel Core i7-13700F/16GB/1TB SSD/RTX 4060', 'Torre', '1199.00', 10, 'El MAG Infinite S3 de MSI ofrece una experiencia gaming superior, combinando rendimiento e\ninnovación. Con un diseño elegante y líneas afiladas, garantiza una buena ventilación y cuenta\ncon iluminación RGB personalizable. Facilita las actualizaciones de componentes y presenta un\ndiseño único con panel lateral transparente. Especificaciones incluyen procesador Intel Core i7-\n13700F, 16GB de RAM DDR5, SSD M.2 de 1TB y gráficos GeForce RTX 4060. Conectividad\ncompleta y fuente de alimentación de 500W ATX 80PLUS BRONZE. Dimensiones: 173.8 x 446.97\nx 407.17 mm. Color: Negro.', 'Torres/MSIMAGInfinite/Im1.jpg', 'Torres/MSIMAGInfinite/Im2.jpg', 0),
('MSI MEG Trident X 12VTF-228XES Intel Core i7-12700KF/32GB/2TB + 1TB SSD/RTX 3080Ti', 'Torre', '2799.00', 10, 'La serie MEG de MSI busca trascender los productos gaming actuales con su modelo insignia, el MEG Trident, un sobremesa gaming compacto que incluye componentes de alto rendimiento en una caja de solo 10 litros. Equipado con procesadores Intel® Core™ de 12ª Gen y tarjetas gráficas NVIDIA® GeForce® RTX, el MEG Trident ofrece una experiencia inalámbrica extraordinaria con Wi-Fi 6E y BT 5.2. Con características como fácil actualización y diseño de panel lateral de cristal templado, el MEG Trident redefine la experiencia gaming.', 'Torres/MSIMEG/Im1.jpg', 'Torres/MSIMEG/Im2.jpg', 0),
('MSI Modern 15 B7M-041XES AMD Ryzen 5 7530U/16GB/512GB SSD/15.6"', 'Portatil', '499.00', 10, 'El Modern 15 B7M de MSI, equipado con un procesador AMD Ryzen™, es increíblemente ligero y delgado, perfecto para mantener tu productividad y entretenimiento en movimiento. Con un diseño único y elegante, este portátil ofrece un rendimiento excepcional en multitarea, edición multimedia y juegos casuales. Su peso de 1,75 kg y su delgadez lo hacen altamente portátil. Cuenta con un panel táctil ampliado, teclado retroiluminado y una función de 180° lay-flat para una mayor productividad. Además, ofrece Wi-Fi 6E para una conectividad rápida y estable. Especificaciones: Procesador AMD Ryzen™ 5 7530U, 16GB de RAM DDR IV, 512GB NVMe PCIe Gen3x4 SSD, pantalla FHD de 15.6", gráficos AMD Radeon™ integrados. Sistema operativo: FreeDOS. Dimensiones: 359 x 241 x 19.9 mm. Peso: 1,75 kg. Color: Negro.', 'Portatiles/MSIModern/Im1.jpg', 'Portatiles/MSIModern/Im2.jpg', 0),
('MSI MPG B550 GAMING PLUS', 'Placa base', '119.90', 10, 'La placa base MPG B550 GAMING PLUS es compatible con procesadores AMD Ryzen de tercera generación y futuros procesadores AMD Ryzen con actualización del BIOS. Admite memoria DDR4 hasta 4400 MHz (OC) y ofrece una experiencia de juego rápida con PCIe 4.0, Lightning Gen 4 x4 M.2, y AMD Turbo USB 3.2 GEN 2. Presenta un diseño de potencia mejorado con Core Boost, PWM IC digital, PCB de cobre espesado de 2 oz y DDR4 Boost. Cuenta con solución térmica premium, blindaje de E / S preinstalado y botón Flash BIOS con función ClearCMOS optimizada. Además, incluye Audio Boost para una calidad de sonido de estudio. Especificaciones: Soporte para procesadores AM4, chipset AMD B550, interfaces gráficas PCIe 4.0/3.0 x16, DisplayPort, HDMI, 4 DIMMs DDR4, almacenamiento M.2 Gen4 x4 y Gen3 x4, puertos USB 3.2 Gen 2 y Gen 1, LAN Gigabit Realtek RTL8111H y audio HD de 8 canales con Audio Boost.', 'PlacasBases/MSIMPG/Im1.jpg', 'PlacasBases/MSIMPG/Im2.jpg', 0),
('MSI MPG CORELIQUID D240 Kit de Refrigeración Líquida Negro', 'Refrigeracion', '264.78', 10, 'La serie MPG de MSI ofrece productos con un estilo único y una actitud desafiante hacia el mundo del gaming. Con un rendimiento excepcional y un diseño vanguardista, la serie MPG marca el futuro de la moda en el mundo del gaming. El MSI MPG CORELIQUID D240 cuenta con características como el TORX FAN 4.0 para una refrigeración óptima, un VENTILADOR TORX 3.0 de 60 mm para disipación de calor, y una pantalla IPS personalizable de 2,4" para monitorizar el hardware y visualizar contenido multimedia. Además, ofrece control independiente de la velocidad del ventilador y la bomba, soporte para los últimos zócalos de CPU y un diseño de tubo de plástico de malla de tres capas para una mayor durabilidad.', 'Refrigeraciones/MSIMPG/Im1.jpg', 'Refrigeraciones/MSIMPG/Im2.jpg', 0),
('MSI Titan GT77 HX 13VH-008ES Intel Core i9-13980HX/64GB/2TB SSD/RTX 4080/17.3" + Bundle Gaming', 'Portatil', '5196.58', 9, 'El Titan GT77 HX es un hito en los juegos, con GPU NVIDIA® GeForce RTX™ serie 40 que ofrecen un rendimiento revolucionario con tecnología DLSS 3 impulsada por IA. El teclado Cherry MX Ultra Low Profile garantiza una experiencia táctil precisa. Características: Procesador Intel® Core™ i9-13980HX, GPU RTX™ 4090/4080, pantalla UHD de 17.3", teclado mecánico RGB Cherry de SteelSeries, batería de 99,9 Wh, delgado y ligero. Especificaciones: Procesador Raptor Lake i9-13980HX, 32GB DDR5, 2TB SSD NVMe PCIe Gen4x4, GPU RTX 4080, Wi-Fi 6E, cámara HD IR, teclado mecánico RGB Cherry, batería de 99.99Whr, Windows 11 Home Advanced. Dimensiones: 397 x 330 x 23 mm. Peso: 3.3 kg. Color: Negro. Accesorios incluidos.', 'Portatiles/MSITitan/Im1.jpg', 'Portatiles/MSITitan/Im2.jpg', 0),
('Nox Hummer GD750 750W 80 Plus Gold', 'Fuente alimentación', '91.98', 10, 'La serie Hummer GD de Nox ofrece fuentes de alimentación con certificación 80 PLUS Gold, garantizando una eficiencia del 90%. Están diseñadas para proporcionar potencia estable y alto rendimiento en equipos de alto rendimiento. Equipadas con un ventilador de 120 mm térmicamente controlado, las Hummer GD solo activan su máxima potencia cuando es necesario, manteniendo una baja sonoridad y una temperatura óptima. Su diseño completamente negro, tanto en el interior como en el exterior, junto con cables negros y planos, facilita la gestión del cableado y asegura un flujo de aire óptimo en el interior del equipo. Las especificaciones incluyen una potencia de 750W, diversos conectores y protecciones, con dimensiones de 150 x 140 x 86 mm y un peso de 1,73 kg.', 'FuentesAlimentacion/NoxHummer/Im1.jpg', 'FuentesAlimentacion/NoxHummer/Im2.jpg', 0),
('NZXT Kraken Elite 360 Kit de Refrigeración Líquida', 'Refrigeracion', '331.74', 10, 'El NZXT Kraken Elite 360 ofrece un rendimiento excepcional, una fácil instalación y una pantalla LCD para visualizar especificaciones del sistema o imágenes personalizadas. Destaca por su personalización a través del software NZXT CAM, su pantalla LCD de 2.36" con alta resolución y frecuencia de actualización, y una bomba de alto rendimiento de Asetek. Además, cuenta con ventiladores de presión estática para una refrigeración potente y silenciosa, tubos reforzados para una manipulación sin preocupaciones, y compatibilidad con una amplia gama de procesadores Intel y AMD. Especificaciones incluyen diámetro de ventilador de 12 cm, soporte para varios sockets de procesador, flujo de aire máximo de 78.02 cfm, y velocidad de motor de bomba de hasta 2800 RPM.', 'Refrigeraciones/NZXTKraken/Im1.jpg', 'Refrigeraciones/NZXTKraken/Im2.jpg', 0),
('PcWor iCUE i7 13700KF/32GB RAM/1TB SSD/RTX 4070 Ti 12GB + Windows 11 - Pc Gaming Negro', 'Torre', '2599.00', 10, 'Los nuevos PcWor ofrecen un rendimiento excepcional y optimización para juegos. Equipados con procesadores Intel Core i7 y potentes gráficas Nvidia RTX, estos PCs garantizan una experiencia de juego inigualable. La tecnología iCUE de Corsair unifica todos los componentes, permitiendo personalización y control avanzados. Con arquitectura NVIDIA Ampere, aceleración IA de DLSS y baja latencia gracias a NVIDIA Reflex, estos PCs ofrecen lo último en tecnología de juegos. Montados y probados por profesionales, incluyen Windows 11 Home 64Bits instalado y configurado. Incluye licencia digital de un solo uso.', 'Torres/PcComiCUE/Im1.jpg', 'Torres/PcComiCUE/Im2.jpg', 0),
('PcWor Imperial Intel Core i7 -14700KF/32GB/2TB SSD/RTX 4070 Ti Super + Windows 11 Home', 'Torre', '2279.00', 10, 'El PcWor Imperial ofrece un excelente rendimiento y relación calidad-precio. Equipado con un procesador Intel Core i7, 32GB de RAM DDR5, un SSD NVMe de 2TB y una gráfica Nvidia RTX 4070 Ti Super, es ideal para usuarios domésticos u oficinistas. Viene con Windows 11 Home 64Bits preinstalado. La caja Corsair iCUE 4000X RGB y la fuente de alimentación Forgeon Bolt PSU 850W garantizan un montaje eficiente y confiable. Con conexiones frontales y traseras versátiles, refrigeración líquida y garantía completa con entrega a domicilio. Se advierte sobre posibles variaciones de componentes debido a disponibilidad.', 'Torres/PcComImperial/Im1.jpg', 'Torres/PcComImperial/Im2.jpg', 0),
('PcWor Lite AMD Ryzen 5500/16GB/1TB SSD/RX 6650 XT', 'Torre', '699.00', 10, 'El PcWor Lite es un PC de alta calidad con un rendimiento potente y una garantía sólida, ideal\npara uso doméstico u oficinas. Equipado con un procesador AMD Ryzen 5, 16GB de RAM DDR4\ny un SSD de 1TB M.2, ofrece un rendimiento óptimo para una variedad de tareas.\nEspecificaciones incluyen una caja Nfortec Caelum Black RGB, fuente de alimentación Corsair\nCV650, tarjeta gráfica MSI AMD Radeon RX 6650 XT MECH 2X OC 8GB GDDR6, y varias\nconexiones USB, HDMI y DisplayPort. Dimensiones: 372 x 200 x 443 mm. Garantía completa\ncon servicio de recogida y entrega.', 'Torres/PcComLite/Im1.jpg', 'Torres/PcComLite/Im2.jpg', 0),
('PcWor Ready AMD Ryzen 5 5600X/16GB/1TB SSD/RTX 4060 + Windows 11 Home', 'Torre', '1049.00', 6, 'El PcWor Ready es un PC gaming con un potente procesador AMD Ryzen 5, 16GB de RAM DDR4, disco SSD de 1TB M.2 NVMe y gráfica Nvidia RTX 4060. Ideal para uso doméstico u oficinas, viene con Windows 11 Home 64Bits instalado. Especificaciones incluyen caja MSI MAG FORGE M100R, fuente MSI MAG A650BN 650W, y refrigeración líquida Cooler Master.\nConexiones delanteras incluyen entrada/salida de audio y puertos USB, mientras que las traseras ofrecen varios puertos USB, HDMI, VGA, DVI-D, y Ethernet. El equipo está montado, testeado y cuenta con garantía completa con recogida y entrega a domicilio.', 'Torres/PcComReadyRyzen5/Im1.jpg', 'Torres/PcComReadyRyzen5/Im2.jpg', 0),
('PcWor Ready AMD Ryzen 7 5800X/32GB/1TB SSD/RTX 4060 Ti', 'Torre', '1149.00', 10, 'El PcWor Ready ofrece una excelente relación calidad/precio con componentes de primeras\nmarcas, garantía máxima y gran rendimiento. Equipado con un procesador AMD Ryzen 7, 32GB\nde RAM DDR4, disco SSD de 1TB M.2 NVMe y gráfica Nvidia RTX 4060 Ti, es ideal para uso general\nen hogar u oficina. Especificaciones incluyen caja Nfortec Krater X, fuente Corsair CV650, CPU\nRyzen 7 5800X, placa ASUS PRIME B550M-A, SSD WD Blue SN570, RAM Kingston FURY Beast,\ngráfica ASUS Dual GeForce RTX 4060 Ti OC Edition y refrigeración Cooler Master MasterLiquid\nML240L V2 RGB. Conexiones frontales y traseras completas. Dimensiones: 420mm x 216mm x\n489mm. Equipo montado, testeado y garantizado con recogida y entrega a domicilio.', 'Torres/PcComReadyRyzen7/Im1.jpg', 'Torres/PcComReadyRyzen7/Im2.jpg', 0),
('PcWor Ready Intel Core i5-12400F/16GB/1TB SSD/RTX 3060', 'Torre', '829.00', 10, 'Los PcWor Ready son equipos gaming configurados para ofrecer una experiencia fluida y\nrápida. Con procesador Intel Core i5, 16GB de RAM DDR4, SSD de 1TB NVMe y gráfica Nvidia RTX\n3060 de 12GB, son ideales para uso doméstico u oficinas. Incluyen caja MSI MAG Forge 100M,\nfuente Corsair CV650 80 Plus Bronze, y conectividad Wi-Fi 6 y Bluetooth 5.2. Dimensiones: 421\nx 210 x 499 mm. Garantía completa.', 'Torres/PcComReadyIntel/Im1.jpg', 'Torres/PcComReadyIntel/Im2.jpg', 0),
('PcWor Ultimate Intel Core i9-14900K/64GB/2TB SSD/RTX 4080 Super + Windows 11 Home', 'Torre', '3289.00', 10, 'El PcWor Imperial ofrece una excelente relación calidad/precio con componentes de primeras marcas, ideal para usuarios que buscan un PC versátil para uso general en el hogar u oficina.\nEquipado con un potente procesador Intel Core i9, 64GB de RAM DDR5, un disco SSD de 2TB M.2 NVMe y una potente gráfica Nvidia RTX 4080 Super, garantiza un rendimiento óptimo. Incluye Windows 11 Home 64Bits y cuenta con una garantía completa. Los componentes pueden variar según disponibilidad, pero siempre se asegura un rendimiento similar.', 'Torres/PcComUltimate/Im1.jpg', 'Torres/PcComUltimate/Im2.jpg', 0),
('PcWor Work AMD Ryzen 5 5600G/16GB/500GB SSD', 'Torre', '439.00', 10, 'El PcWor Work ofrece una excelente relación calidad/precio con componentes de primeras\nmarcas, ideal para usuarios domésticos u oficinas. Equipado con un procesador AMD Ryzen 5\n5600G, 16GB de RAM DDR4, y un disco SSD de 500GB M.2 NVMe, proporciona un rendimiento\nsólido en diversas tareas. Especificaciones: Caja Antec NX500M ARGB M-ATX, fuente de\nalimentación 500W, placa base Gigabyte B550M K, tarjeta gráfica Radeon™ Graphics\nintegrada, y diversas conexiones USB 2.0 y 3.2 Gen 1. Dimensiones: 483mm x 200mm x\n451mm. Equipo completamente montado y probado, con garantía completa y servicio de\nrecogida y entrega a domicilio.', 'Torres/PcComWork/Im1.jpg', 'Torres/PcComWork/Im2.jpg', 0),
('PcWor Work AMD Ryzen 5 5600G/16GB/500GB SSD + Windows 11 Home', 'Torre', '549.00', 10, 'El PcWor Work es un PC de excelente relación calidad/precio, ideal para uso doméstico u\noficinas. Equipado con un procesador AMD Ryzen 5 5600G, 16GB de RAM DDR4, y un SSD de\n500GB NVMe, ofrece alto rendimiento. Incluye Windows 11 Home 64Bits. Características: caja\nAntec NX500M ARGB, fuente de alimentación de 500W, tarjeta gráfica Radeon™ Graphics, y\nconectividad Ethernet y Wi-Fi. Dimensiones: 483mm x 200mm x 451mm. Garantía completa\ncon recogida y entrega.', 'Torres/PcComWorkWindows/Im1.jpg', 'Torres/PcComWorkWindows/Im2.jpg', 0),
('PNY Nvidia Tesla P40 24GB GDDR5', 'Tarjeta Grafica', '9794.56', 9, 'Altura: 111,2 mm; Ancho de banda de memoria (max): 346 GB/s; Ancho de datos: 384 bit; CUDA: Si; Capacidad memoria de adaptador gráfico: 24 GB; Color del producto: Negro, Verde; Conectores de energia suplementario: 1x 8-pin; Consumo energético: 250 W; Familia de procesadores de gráficos: NVIDIA; Núcleos CUDA: 3840; Número de ranuras: 2; Peso: 968 g; Procesador gráfico: Tesla P40; Profundidad: 267,7 mm; Rendimiento máximo de punto flotante de precisión única: 12000 Gflops; Tipo de enfriamiento: Pasivo; Tipo de interfaz: PCI Express x16 3.0; Tipo de memoria de adaptador gráfico: GDDR5.', 'TarjetasGraficas/NvidiaTesla/Im1.jpg', 'TarjetasGraficas/NvidiaTesla/Im2.jpg', 0),
('PowerColor HELLHOUND AMD Radeon RX 7900 XTX 24GB GDDR6', 'Tarjeta Grafica', '979.00', 10, 'El producto Hellhound ofrece una experiencia de juego confiable y elegante, con características como la tecnología de super resolución AMD FidelityFX™ para mejorar la calidad de imagen y el rendimiento, optimización para Windows 11, arquitectura AMD RDNA™ 3 con hardware de trazado de rayos, y tecnología AMD FreeSync™ para una experiencia de juego sin tartamudeos. Las especificaciones de la PowerColor HELLHOUND AMD Radeon RX 7900 XTX incluyen un procesador Radeon RX 7900 XTX con 24 GB de memoria GDDR6, interfaz PCI Express 4.0, y características de diseño como iluminación LED.', 'TarjetasGraficas/AMDRadeonRX/Im1.jpg', 'TarjetasGraficas/AMDRadeonRX/Im2.jpg', 0),
('PRUEBA1', 'Portatil', '229.00', 4, 'El Acer Aspire 1 ofrece funcionalidad práctica en cualquier lugar a un bajo costo. Con un diseño "Pearl White", el procesador Qualcomm® Snapdragon™ 7c, la batería de 20 horas y la tecnología 4G LTE hacen de este dispositivo una opción versátil y preparada para los desafíos diarios. Características: Batería duradera de hasta 20 horas. Portabilidad gracias al procesador Snapdragon™ 7c de bajo consumo. Conectividad con puertos USB Type-C y USB 3.2 Type-A Gen 1. Especificaciones de Acer Aspire 1 Qualcomm: Procesador Qualcomm Snapdragon SC7180 2.4 GHz. 8 GB de RAM DDR4X. Almacenamiento eMMC de 128 GB. Pantalla LCD LED de 14" HD.Controlador gráfico Qualcomm® Adreno 618. Conectividad Wi-Fi 802.11ac y Bluetooth 5.0. Batería de 48Wh. Puertos USB 3.2 Gen. 2 tipo C y USB 3.2 de segunda generación. Sistema operativo Windows 11 Home 64 Bits. Dimensiones: 328 x 236 x 18,90 mm. Peso: 1,5 kg.Color: Blanco.', 'Portatiles/AcerAspire/Im1.jpg', 'Portatiles/AcerAspire/Im2.jpg', 1),
('PRUEBA2', 'Portatil', '729.00', 10, 'El Acer Nitro V 15 lleva tus aventuras gaming a otro nivel, combinando potencia y estilo en un portátil excepcional. Equipado con un procesador Intel® Core™ i5-13420H de 13.ª generación, ofrece un rendimiento superior con almacenamiento y RAM DDR5 de alta velocidad. Su pantalla Full HD de 15,6 pulgadas con frecuencia de actualización de hasta 144Hz te sumerge en un mundo de gaming vibrante. Los innovadores ventiladores mantienen la temperatura bajo control incluso en las batallas más intensas. Con Wi-Fi 6, Ethernet Gigabit y la aplicación NitroSense, estarás siempre listo para la acción. Especificaciones: Procesador Intel® Core™ i5- 13420H, 16GB de RAM DDR5 (ampliable hasta 32GB), 1024GB PCIe NVMe SSD (ampliable hasta 2TB), tarjeta gráfica NVIDIA® GeForce RTX™ 3050 6G-GDDR6, entre otros. Sistema operativo: Sin sistema operativo. Dimensiones: 362.3 x 239.89 x 22.9/26.9 mm. Peso: 2,1 kg. Color: Negro.', 'Portatiles/AcerNitro/Im1.jpg', 'Portatiles/AcerNitro/Im2.jpg', 0),
('PRUEBA3', 'Portatil', '920.05', 10, 'El Triton 500 SE es un portátil gaming delgado y elegante diseñado para multitarea, rendimiento extremo y creatividad. Con un procesador Intel Core i7-11800H, 32GB de memoria DDR4, y almacenamiento SSD PCIe NVMe de 1024GB, ofrece un potente rendimiento. La pantalla de 16" WQXGA con una frecuencia de actualización de 165Hz y la tarjeta gráfica NVIDIA GeForce RTX 3080 garantizan una experiencia visual inmersiva. Con conectividad Bluetooth 5.1, Wi-Fi 6, y Thunderbolt 4. Incluye Windows 11 Home, cámara HD, micrófono, y lector de huellas. Dimensiones: 358.5 x 262.4 x 19.9 mm. Peso: 2.4 kg. Color: Gris. Incluye 1 mes de Xbox Game Pass Ultimate.', 'Portatiles/AcerPredator/Im1.jpg', 'Portatiles/AcerPredator/Im2.jpg', 0),
('PRUEBA4', 'Memoria RAM', '129.99', 7, 'La memoria Predator Vesta II DDR5 lleva el rendimiento de juego y computación a nuevas alturas con su velocidad ultrarrápida, diseño elegante y iluminación RGB personalizable. Con componentes de calidad y overclocking fácil, es ideal para cualquier tarea intensiva en la computadora. Sus características incluyen iluminación RGB brillante, ICS clasificados a mano para tiempos ultrabajos, compatibilidad con placas base y CPU de primer nivel, y ECC integrado para la corrección de errores. Además, cuenta con un elegante disipador de calor metálico con sensor de temperatura integrado y PMIC programable para mejorar la estabilidad del sistema. Con Intel XMP 3.0 para overclocking de un clic y una garantía limitada de por vida, la Predator Vesta II es una opción líder en rendimiento y estilo.', 'MemoriaRAM/AcerPredator/Im1.jpg', 'MemoriaRAM/AcerPredator/Im2.jpg', 1),
('Razer Blade 15 Advanced Model QHD Intel Core i7-12800H/32 GB/1TB SSD/RTX 3080Ti/15.6"', 'Portatil', '5266.69', 9, 'Experimente el rendimiento de vanguardia con los procesadores Intel® Core™ i7 e i9 de 12.ª generación, diseñados para tareas creativas y de juegos exigentes. Las GPU NVIDIA® GeForce RTX™ 30 ofrecen gráficos realistas y funciones de IA avanzadas. Disfrute de una experiencia más rápida con memoria DDR5 de hasta 4800MHz. Las pantallas de 15,6" con opciones de hasta 4K ofrecen una experiencia de visualización inmersiva. El Razer Blade 15 optimiza la disipación de calor para un rendimiento térmico óptimo. Personalice el teclado RGB con Chroma™. Equipado con Wi-Fi 6E, Bluetooth® 5.2, Thunderbolt™ 4 y una variedad de puertos. Especificaciones: Procesador Intel Core i7-12800H, 32GB RAM DDR5, 1TB SSD PCIe 4.0, NVIDIA GeForce RTX 3080 Ti, pantalla QHD de 240Hz, conectividad avanzada, teclado retroiluminado, batería de 80WHr, Windows 11 Home 64 bits. Color: Negro.', 'Portatiles/RazerBlade/Im1.jpg', 'Portatiles/RazerBlade/Im2.jpg', 0),
('Samsung 870 QVO SSD 8TB SATA3', 'Disco duro', '509.00', 10, 'El 870 QVO de Samsung es la última incorporación a su línea de SSD de segunda generación. Ofrece hasta 8 TB de almacenamiento y un rendimiento mejorado en comparación con su predecesor, el 860 QVO. Con velocidades secuenciales de hasta 560/530 MB/s y una mayor fiabilidad de hasta 2.880 TBW, es una opción ideal para usuarios que deseen ampliar la capacidad de almacenamiento de su PC o portátil. El software Samsung Magician facilita la gestión del disco, mientras que la calidad y confiabilidad de los componentes internos aseguran un rendimiento óptimo', 'DiscosDuros/Samsung870/Im1.jpg', 'DiscosDuros/Samsung870/Im2.jpg', 0),
('Seagate FireCuda 530 SSD 4TB M.2 NVMe 3D TLC', 'Disco duro', '637.87', 10, 'El FireCuda® 530 ofrece un rendimiento impresionante con velocidades de hasta 7300 MB/s, aprovechando PCIe® Gen4 para juegos y aplicaciones de alta potencia. Es la unidad SSD más rápida de Seagate hasta la fecha, con componentes avanzados y durabilidad excepcional. Con controlador E18 validado y NAND SSD 3D TLC, garantiza un rendimiento y resistencia óptimos. Incluye cinco años de garantía limitada y tres años de servicios de recuperación de datos.', 'DiscosDuros/SeagateFireCuda/Im1.jpg', 'DiscosDuros/SeagateFireCuda/Im2.jpg', 0),
('Seasonic Prime TX-1300 1300W 80 Plus Titanium Modular', 'Fuente alimentación', '590.41', 10, 'La serie PRIME de Seasonic, como parte de su One Seasonic Initiative, ha lanzado las series PRIME TX, PRIME PX y PRIME GX, sucesoras de las series Seasonic PRIME y PRIME Ultra. Estas nuevas series mantienen el rendimiento sobresaliente y la calidad tecnológica de la marca. Cada modelo cuenta con características distintivas y especificaciones únicas. Destacan por ser completamente modulares, certificadas como 80 PLUS Titanium y ofrecen una garantía de 12 años. Con dimensiones compactas y un diseño actualizado, estas fuentes de alimentación ofrecen eficiencia energética, control de ventilador híbrido y protecciones avanzadas.', 'FuentesAlimentacion/SeasonicPrime/Im1.jpg', 'FuentesAlimentacion/SeasonicPrime/Im2.jpg', 0),
('Synology SAT5200 2.5" SSD 1.92TB SATA 3', 'Disco duro', '1573.79', 10, 'La SSD SATA SAT5200 de Synology garantiza un rendimiento estable de E/S y una latencia reducida para servicios y aplicaciones críticas. Diseñada para cargas de trabajo intensivas, ofrece hasta 67 000 IOPS de escritura aleatoria 4K, protección integral de datos y análisis de vida útil basado en la carga de trabajo real. Además, cuenta con un diseño de circuito de protección contra pérdida de energía y notificaciones oportunas para planificar el rendimiento y la longevidad del sistema. Esta SSD está especialmente diseñada para los sistemas Synology, con pruebas exhaustivas de compatibilidad y calidad.', 'DiscosDuros/SynologySAT5200/Im1.jpg', 'DiscosDuros/SynologySAT5200/Im2.jpg', 0),
('Team Group Delta White RGB DDR4 3200 PC4-25600 16GB 2x8GB CL16', 'Memoria RAM', '46.98', 10, 'Características: Efecto de iluminación RGB de 120°, deslumbrante y amplio. Diseño minimalista asimétrico para mejor disipación de calor. Control de iluminación con T-FORCE BLITZ (versión beta). Compatibilidad con varios softwares de control de iluminación. Mayor rendimiento con JEDEC RC 2.0. Tecnología de overclocking XMP2.0. Bajo consumo de energía. Aprobación QVL de fabricantes de placas base. Especificaciones: Capacidad de memoria interna de 16GB DDR4 a 3200 MHz. Formato de 288-pin DIMM. Sin búfer, sin ECC. Latencia CAS de 16. Voltaje de memoria de 1.35V. Diseño con disipador térmico y retroiluminación en RGB. Soporte para sistemas operativos Windows y Linux.', 'MemoriaRAM/TeamGroup/Im1.jpg', 'MemoriaRAM/TeamGroup/Im2.jpg', 0),
('Tempest Liquid Cooler 120 RGB Kit de Refrigeración Líquida 120mm Negro', 'Refrigeracion', '49.99', 10, 'Tempest presenta la nueva refrigeración líquida Tempest Gaming Liquid Cooler 360, ahora en blanco, su refrigerador AIO más grande con iluminación RGB efecto Rainbow. Destaca por su potencia y eficiencia, ofreciendo una instalación sencilla y un diseño estético que ilumina tu equipo. Compatible con Intel y AMD, con capacidad de overclocking y fácil limpieza. Especificaciones: Compatible con varios sockets, ventiladores de 120 mm, tamaño del radiador de 394x120x27 mm, entre otros.', 'Refrigeraciones/TempestLiquidCooler120/Im1.jpg', 'Refrigeraciones/TempestLiquidCooler120/Im2.jpg', 0),
('Tempest Liquid Cooler 360 Kit de Refrigeración Líquida Blanco', 'Refrigeracion', '69.99', 9, 'Tempest presenta la nueva refrigeración líquida Tempest Gaming Liquid Cooler 360, ahora en blanco, su refrigerador AIO más grande con iluminación RGB efecto Rainbow. Destaca por su potencia y eficiencia, ofreciendo una instalación sencilla y un diseño estético que ilumina tu equipo. Compatible con Intel y AMD, con capacidad de overclocking y fácil limpieza. Especificaciones: Compatible con varios sockets, ventiladores de 120 mm, tamaño del radiador de 394x120x27 mm, entre otros.', 'Refrigeraciones/TempestLiquidCooler360/Im1.jpg', 'Refrigeraciones/TempestLiquidCooler360/Im2.jpg', 0),
('UNYKAch Fuente de Alimentación ATX 500W', 'Fuente alimentación', '11.55', 10, 'La fuente de alimentación Unykach 52099 ofrece estabilidad y protección para un funcionamiento seguro de los componentes de la computadora, con un diseño compacto y eficiente. Potencia total: 500 W. Voltaje de entrada AC: 230 V. Eficiencia: 78%. Protecciones: Sobreintensidad, Sobretensión, Sobrevoltaje, Sobrecalentamiento, Sobrecarga, . Cortocircuito, Bajo voltaje. Conectividad: 20+4 pin ATX, 3 conectores de energía SATA, 2 conectores periféricos (Molex), 1 conector floppy. Formato: ATX. Nivel de ruido: 28 dB. Certificaciones: EN60950, TÜV. Diseño: Color plata, ventilador de 12 cm, interruptor de encendido/apagado integrado. Dimensiones: 150 x 140 x 85 mm. Peso: 747 g', 'FuentesAlimentacion/UNYKAch/Im1.jpg', 'FuentesAlimentacion/UNYKAch/Im2.jpg', 0),
('Zotac Gaming GeForce RTX 3060 Twin Edge LHR 12GB GDDR6', 'Tarjeta Grafica', '291.99', 10, 'La serie ZOTAC GAMING GeForce RTX™ 30 ofrece un rendimiento excepcional con tecnología avanzada, incluyendo trazado de rayos en tiempo real, DLSS, NVIDIA Reflex, y soporte para aplicaciones creativas. Con arquitectura NVIDIA Ampere y DLSS, proporciona un juego de próxima generación. Compatible con DirectX 12 Ultimate y cuenta con tecnología IceStorm 2.0 para enfriamiento avanzado. Requiere un suministro de energía mínimo de 600 W y es compatible con Windows 10 x64. Este producto incluye un manual de usuario y viene empaquetado en una caja de dimensiones 218 mm x 83 mm x 283 mm.', 'TarjetasGraficas/ZotacGaming/Im1.jpg', 'TarjetasGraficas/ZotacGaming/Im2.jpg', 0);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `cesta`
--
ALTER TABLE `cesta`
  ADD PRIMARY KEY (`IdCliente`,`IdProducto`),
  ADD KEY `IdProducto` (`IdProducto`);

--
-- Indices de la tabla `datos_clientes`
--
ALTER TABLE `datos_clientes`
  ADD PRIMARY KEY (`Usuario`);

--
-- Indices de la tabla `lista_deseos`
--
ALTER TABLE `lista_deseos`
  ADD PRIMARY KEY (`IdCliente`,`IdProducto`),
  ADD KEY `IdProducto` (`IdProducto`);

--
-- Indices de la tabla `productos`
--
ALTER TABLE `productos`
  ADD PRIMARY KEY (`IdNombre`);

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `lista_deseos`
--
ALTER TABLE `lista_deseos`
  ADD CONSTRAINT `lista_deseos_ibfk_1` FOREIGN KEY (`IdCliente`) REFERENCES `datos_clientes` (`Usuario`),
  ADD CONSTRAINT `lista_deseos_ibfk_2` FOREIGN KEY (`IdProducto`) REFERENCES `productos` (`IdNombre`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
